//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg_common.proto
// Note: requires additional types generated from: enum_define.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMessageEmpty")]
  public partial class PBMessageEmpty
  {
    public PBMessageEmpty() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroCardData")]
  public partial class PBHeroCardData
  {
    public PBHeroCardData() {}
    
    // TYPE_UINT32 : hero_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint hero_id = default(uint);
  
    // TYPE_UINT32 : hero_gid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hero_gid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint hero_gid = default(uint);
  
    // TYPE_INT32 : level
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int level = default(int);
  
    // TYPE_INT32 : exp
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int exp = default(int);
  
    // TYPE_INT32 : ascension_level
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ascension_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int ascension_level = default(int);
  
    // TYPE_INT32 : red_star_level
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"red_star_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int red_star_level = default(int);
  
    // TYPE_INT32 : skill_level
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"skill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int skill_level = default(int);
  
    // TYPE_UINT32 : team_id
    [global::ProtoBuf.ProtoMember(8, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> team_id = new global::System.Collections.Generic.List<uint>();
  
    // TYPE_BOOL : locked
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"locked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool locked = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroCards")]
  public partial class PBHeroCards
  {
    public PBHeroCards() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroCardData : heroes
    [global::ProtoBuf.ProtoMember(1, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroCardData> heroes = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroCardData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroTeamData")]
  public partial class PBHeroTeamData
  {
    public PBHeroTeamData() {}
    
    // TYPE_UINT32 : team_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint team_id = default(uint);
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroMember : hero_members
    [global::ProtoBuf.ProtoMember(2, Name=@"hero_members", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroMember> hero_members = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroMember>();
  
    // TYPE_STRING : team_name
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"team_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string team_name = "";
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroMember")]
  public partial class PBHeroMember
  {
    public PBHeroMember() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : hero_gid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hero_gid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint hero_gid = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingData")]
  public partial class PBBuildingData
  {
    public PBBuildingData() {}
    
    // TYPE_UINT32 : building_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint building_id = default(uint);
  
    // TYPE_UINT32 : building_pos
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"building_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint building_pos = default(uint);
  
    // TYPE_ENUM.FunPlus.Common.Config.ESBuildingState : building_state
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"building_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FunPlus.Common.Config.ESBuildingState.Building_State_Idle)]
	public FunPlus.Common.Config.ESBuildingState building_state = FunPlus.Common.Config.ESBuildingState.Building_State_Idle;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBProgress : build_progress
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"build_progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBProgress build_progress = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBProgress : collect_progress
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"collect_progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBProgress collect_progress = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingProduce : produce_progress
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"produce_progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingProduce produce_progress = null;
  
    // TYPE_BOOL : is_new
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_new", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool is_new = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildings")]
  public partial class PBBuildings
  {
    public PBBuildings() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : buildings
    [global::ProtoBuf.ProtoMember(1, Name=@"buildings", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBBuildingData> buildings = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBBuildingData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampaignData")]
  public partial class PBCampaignData
  {
    public PBCampaignData() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
    // TYPE_ENUM.FunPlus.Common.Config.ESCampaignReward : isrewards
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isrewards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FunPlus.Common.Config.ESCampaignReward.UnReceived)]
	public FunPlus.Common.Config.ESCampaignReward isrewards = FunPlus.Common.Config.ESCampaignReward.UnReceived;
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampaigns")]
  public partial class PBCampaigns
  {
    public PBCampaigns() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBCampaignData : campaigns
    [global::ProtoBuf.ProtoMember(1, Name=@"campaigns", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBCampaignData> campaigns = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBCampaignData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBItemValue")]
  public partial class PBItemValue
  {
    public PBItemValue() {}
    
    // TYPE_UINT32 : item_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint item_id = default(uint);
  
    // TYPE_UINT32 : count
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint count = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBItemData")]
  public partial class PBItemData
  {
    public PBItemData() {}
    
    // TYPE_UINT32 : id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint id = default(uint);
  
    // TYPE_UINT32 : item_id
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint item_id = default(uint);
  
    // TYPE_UINT32 : count
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint count = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBTaskData")]
  public partial class PBTaskData
  {
    public PBTaskData() {}
    
    // TYPE_UINT32 : task_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint task_id = default(uint);
  
    // TYPE_BOOL : reward_gained
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward_gained", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool reward_gained = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBTaskDataList")]
  public partial class PBTaskDataList
  {
    public PBTaskDataList() {}
    
    // TYPE_ENUM.FunPlus.Common.Config.ESTaskStatus : task_status
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FunPlus.Common.Config.ESTaskStatus.TaskStatus_Inactive)]
	public FunPlus.Common.Config.ESTaskStatus task_status = FunPlus.Common.Config.ESTaskStatus.TaskStatus_Inactive;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBTaskData : data_list
    [global::ProtoBuf.ProtoMember(2, Name=@"data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBTaskData> data_list = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBTaskData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAchievementData")]
  public partial class PBAchievementData
  {
    public PBAchievementData() {}
    
    // TYPE_ENUM.FunPlus.Common.Config.ESConditionType : conditionType
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"conditionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FunPlus.Common.Config.ESConditionType.ConditionType_BuildingLimit)]
	public FunPlus.Common.Config.ESConditionType conditionType = FunPlus.Common.Config.ESConditionType.ConditionType_BuildingLimit;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACBuildings : buildings
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buildings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACBuildings buildings = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACLotteryTimes : lotteryTimes
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lotteryTimes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACLotteryTimes lotteryTimes = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACHeroLevel : heroLevel
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"heroLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACHeroLevel heroLevel = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACHeroAscend : heroAscend
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"heroAscend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACHeroAscend heroAscend = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACDungeonPass : dungeons
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dungeons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACDungeonPass dungeons = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACDungeonPassTotal : dungeonPassTotal
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dungeonPassTotal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACDungeonPassTotal dungeonPassTotal = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACCampResearch : campResearch
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"campResearch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBACCampResearch campResearch = null;
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACBuildingData")]
  public partial class PBACBuildingData
  {
    public PBACBuildingData() {}
    
    // TYPE_UINT32 : buildingId
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"buildingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint buildingId = default(uint);
  
    // TYPE_UINT32 : buildingCount
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buildingCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint buildingCount = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACBuildings")]
  public partial class PBACBuildings
  {
    public PBACBuildings() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACBuildingData : data
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBACBuildingData> data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBACBuildingData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACLotteryTimes")]
  public partial class PBACLotteryTimes
  {
    public PBACLotteryTimes() {}
    
    // TYPE_UINT32 : times
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint times = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACHeroLevel")]
  public partial class PBACHeroLevel
  {
    public PBACHeroLevel() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACHeroLevelData : data
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBACHeroLevelData> data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBACHeroLevelData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACHeroLevelData")]
  public partial class PBACHeroLevelData
  {
    public PBACHeroLevelData() {}
    
    // TYPE_UINT32 : count
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint count = default(uint);
  
    // TYPE_UINT32 : heroLevel
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint heroLevel = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACHeroAscend")]
  public partial class PBACHeroAscend
  {
    public PBACHeroAscend() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACHeroAscendData : data
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBACHeroAscendData> data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBACHeroAscendData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACHeroAscendData")]
  public partial class PBACHeroAscendData
  {
    public PBACHeroAscendData() {}
    
    // TYPE_UINT32 : count
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint count = default(uint);
  
    // TYPE_UINT32 : heroAscend
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroAscend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint heroAscend = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACDungeonData")]
  public partial class PBACDungeonData
  {
    public PBACDungeonData() {}
    
    // TYPE_UINT32 : dungeonId
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint dungeonId = default(uint);
  
    // TYPE_UINT32 : passTimes
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"passTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint passTimes = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACDungeonPass")]
  public partial class PBACDungeonPass
  {
    public PBACDungeonPass() {}
    
    // TYPE_UINT32 : chapterId
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint chapterId = default(uint);
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBACDungeonData : data
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBACDungeonData> data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBACDungeonData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACDungeonPassTotal")]
  public partial class PBACDungeonPassTotal
  {
    public PBACDungeonPassTotal() {}
    
    // TYPE_UINT32 : times
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint times = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBACCampResearch")]
  public partial class PBACCampResearch
  {
    public PBACCampResearch() {}
    
    // TYPE_UINT32 : campProductId
    [global::ProtoBuf.ProtoMember(1, Name=@"campProductId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> campProductId = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBShopProductData")]
  public partial class PBShopProductData
  {
    public PBShopProductData() {}
    
    // TYPE_UINT32 : id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint id = default(uint);
  
    // TYPE_UINT32 : count
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint count = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBShopData")]
  public partial class PBShopData
  {
    public PBShopData() {}
    
    // TYPE_UINT32 : id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint id = default(uint);
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBShopProductData : products
    [global::ProtoBuf.ProtoMember(2, Name=@"products", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBShopProductData> products = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBShopProductData>();
  
    // TYPE_INT64 : begin_time
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"begin_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
	public long begin_time = default(long);
  
    // TYPE_INT64 : end_time
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
	public long end_time = default(long);
  
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ESTaskStatus")]
    public enum ESTaskStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskStatus_Inactive", Value=1)]
      TaskStatus_Inactive = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskStatus_Active", Value=2)]
      TaskStatus_Active = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskStatus_Finish", Value=3)]
      TaskStatus_Finish = 3
    }
  
}