//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg_bi_data.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBIPlayerLogin")]
  public partial class PBBIPlayerLogin
  {
    public PBBIPlayerLogin() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBILoginAttrs : attrs
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBILoginAttrs attrs = null;
  
    // TYPE_STRING : pid
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string pid = "";
  
    // TYPE_STRING : sid
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string sid = "";
  
    // TYPE_STRING : ts
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string ts = "";
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBILoginAttrs")]
  public partial class PBBILoginAttrs
  {
    public PBBILoginAttrs() {}
    
    // TYPE_STRING : country
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string country = "";
  
    // TYPE_STRING : game_version
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string game_version = "";
  
    // TYPE_STRING : os
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string os = "";
  
    // TYPE_STRING : device_id
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string device_id = "";
  
    // TYPE_STRING : gaid
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gaid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string gaid = "";
  
    // TYPE_STRING : os_version
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"os_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string os_version = "";
  
    // TYPE_STRING : idfa
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"idfa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string idfa = "";
  
    // TYPE_STRING : client_uuid
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"client_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string client_uuid = "";
  
    // TYPE_STRING : device_type
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"device_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string device_type = "";
  
    // TYPE_STRING : res_version
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"res_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string res_version = "";
  
    // TYPE_STRING : time_zone
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"time_zone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string time_zone = "";
  
    // TYPE_STRING : device_lang
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"device_lang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string device_lang = "";
  
    // TYPE_STRING : pkg_channel
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"pkg_channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string pkg_channel = "";
  
    // TYPE_STRING : sdk_version
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"sdk_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string sdk_version = "";
  
    // TYPE_STRING : imei
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"imei", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string imei = "";
  
    // TYPE_STRING : msg_type
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"msg_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string msg_type = "";
  
    // TYPE_STRING : idfv
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"idfv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string idfv = "";
  
    // TYPE_STRING : lang
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"lang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string lang = "";
  
    // TYPE_STRING : android_id
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"android_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string android_id = "";
  
    // TYPE_STRING : app_id
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"app_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string app_id = "";
  
    // TYPE_STRING : app_install_ts
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"app_install_ts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string app_install_ts = "";
  
    // TYPE_STRING : rum_version
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"rum_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
	public string rum_version = "";
  
  }
  
}