//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg_system.proto
// Note: requires additional types generated from: msg_base.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPingMessageRequest")]
  public partial class PBPingMessageRequest
  {
    public PBPingMessageRequest() {}
    
    //  : send_time
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"send_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
	public double send_time = default(double);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPingMessageResponse")]
  public partial class PBPingMessageResponse
  {
    public PBPingMessageResponse() {}
    
    //  : send_time
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"send_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
	public double send_time = default(double);
  
    //  : servertime
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"servertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
	public double servertime = default(double);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLogSettingRequest")]
  public partial class PBLogSettingRequest
  {
    public PBLogSettingRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLogSettingRespose")]
  public partial class PBLogSettingRespose
  {
    public PBLogSettingRespose() {}
    
    // TYPE_INT32 : enable_mode_list
    [global::ProtoBuf.ProtoMember(1, Name=@"enable_mode_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<int> enable_mode_list = new global::System.Collections.Generic.List<int>();
  
    // TYPE_UINT32 : log_level_site
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"log_level_site", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint log_level_site = default(uint);
  
    // TYPE_UINT32 : log_output_site
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"log_output_site", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint log_output_site = default(uint);
  
    // TYPE_BOOL : unity_log_open
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"unity_log_open", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool unity_log_open = default(bool);
  
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EPLogLevel")]
    public enum EPLogLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLOG_LEVEL_ERROR", Value=1)]
      PLOG_LEVEL_ERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLOG_LEVEL_ASSERT", Value=2)]
      PLOG_LEVEL_ASSERT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLOG_LEVEL_WARNING", Value=4)]
      PLOG_LEVEL_WARNING = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLOG_LEVEL_LOG", Value=8)]
      PLOG_LEVEL_LOG = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLOG_LEVEL_EXCEPTION", Value=16)]
      PLOG_LEVEL_EXCEPTION = 16
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ELogOutputMode")]
    public enum ELogOutputMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogOutput_Mode_None", Value=1)]
      LogOutput_Mode_None = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogOutput_Mode_File", Value=2)]
      LogOutput_Mode_File = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogOutput_Mode_Net", Value=4)]
      LogOutput_Mode_Net = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ELogModeType")]
    public enum ELogModeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Unity", Value=0)]
      LogMode_Type_Unity = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Device", Value=1)]
      LogMode_Type_Device = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Net", Value=2)]
      LogMode_Type_Net = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Update", Value=3)]
      LogMode_Type_Update = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Load", Value=4)]
      LogMode_Type_Load = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Task", Value=5)]
      LogMode_Type_Task = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Battle", Value=6)]
      LogMode_Type_Battle = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Team", Value=7)]
      LogMode_Type_Team = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Union", Value=8)]
      LogMode_Type_Union = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Guide", Value=9)]
      LogMode_Type_Guide = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Hero", Value=10)]
      LogMode_Type_Hero = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Building", Value=11)]
      LogMode_Type_Building = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Editor", Value=12)]
      LogMode_Type_Editor = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Player", Value=13)]
      LogMode_Type_Player = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom1", Value=100)]
      LogMode_Type_Custom1 = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom2", Value=101)]
      LogMode_Type_Custom2 = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom3", Value=102)]
      LogMode_Type_Custom3 = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom4", Value=103)]
      LogMode_Type_Custom4 = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom5", Value=104)]
      LogMode_Type_Custom5 = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom6", Value=105)]
      LogMode_Type_Custom6 = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom7", Value=106)]
      LogMode_Type_Custom7 = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom8", Value=107)]
      LogMode_Type_Custom8 = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Custom9", Value=108)]
      LogMode_Type_Custom9 = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogMode_Type_Count", Value=109)]
      LogMode_Type_Count = 109
    }
  
}