//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_hero.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
// Note: requires additional types generated from: enum_define.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllHeroDataRequest")]
  public partial class PBAllHeroDataRequest
  {
    public PBAllHeroDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllHeroDataResponse")]
  public partial class PBAllHeroDataResponse
  {
    public PBAllHeroDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroCardData : heroes
    [global::ProtoBuf.ProtoMember(1, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroCardData> heroes = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroCardData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroLockRequest")]
  public partial class PBHeroLockRequest
  {
    public PBHeroLockRequest() {}
    
    // TYPE_UINT32 : hero_gid
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_gid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint hero_gid = default(uint);
  
    // TYPE_BOOL : locked
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"locked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool locked = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroLockResponse")]
  public partial class PBHeroLockResponse
  {
    public PBHeroLockResponse() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroUpgradeRequest")]
  public partial class PBHeroUpgradeRequest
  {
    public PBHeroUpgradeRequest() {}
    
    // TYPE_UINT32 : hero_gid
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_gid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint hero_gid = default(uint);
  
    // TYPE_UINT32 : material_gid
    [global::ProtoBuf.ProtoMember(2, Name=@"material_gid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> material_gid = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroUpgradeResponse")]
  public partial class PBHeroUpgradeResponse
  {
    public PBHeroUpgradeResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroCardData : hero_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBHeroCardData hero_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroAscendRequest")]
  public partial class PBHeroAscendRequest
  {
    public PBHeroAscendRequest() {}
    
    // TYPE_UINT32 : hero_gid
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_gid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint hero_gid = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroAscendResponse")]
  public partial class PBHeroAscendResponse
  {
    public PBHeroAscendResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroCardData : hero_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBHeroCardData hero_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllHeroTeamDataRequest")]
  public partial class PBAllHeroTeamDataRequest
  {
    public PBAllHeroTeamDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllHeroTeamDataResponse")]
  public partial class PBAllHeroTeamDataResponse
  {
    public PBAllHeroTeamDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroTeamData : team_data
    [global::ProtoBuf.ProtoMember(1, Name=@"team_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroTeamData> team_data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroTeamData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroTeamSaveRequest")]
  public partial class PBHeroTeamSaveRequest
  {
    public PBHeroTeamSaveRequest() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroTeamData : team_data
    [global::ProtoBuf.ProtoMember(1, Name=@"team_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroTeamData> team_data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroTeamData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBHeroTeamSaveResponse")]
  public partial class PBHeroTeamSaveResponse
  {
    public PBHeroTeamSaveResponse() {}
    
  }
  
}