//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_resource.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: enum_define.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllResourceDataRequest")]
  public partial class PBAllResourceDataRequest
  {
    public PBAllResourceDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllResourceDataResponse")]
  public partial class PBAllResourceDataResponse
  {
    public PBAllResourceDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : resources
    [global::ProtoBuf.ProtoMember(1, Name=@"resources", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> resources = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
}