//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_lottery.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLotteryDataRequest")]
  public partial class PBLotteryDataRequest
  {
    public PBLotteryDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLotteryData")]
  public partial class PBLotteryData
  {
    public PBLotteryData() {}
    
    // TYPE_UINT32 : id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint id = default(uint);
  
    // TYPE_UINT32 : free_times
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"free_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint free_times = default(uint);
  
    // TYPE_INT64 : free_reset_time
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"free_reset_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
	public long free_reset_time = default(long);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLotteryDataResponse")]
  public partial class PBLotteryDataResponse
  {
    public PBLotteryDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBLotteryData : datas
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBLotteryData> datas = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBLotteryData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLotteryRequest")]
  public partial class PBLotteryRequest
  {
    public PBLotteryRequest() {}
    
    // TYPE_UINT32 : id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint id = default(uint);
  
    // TYPE_INT32 : roll_type
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roll_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int roll_type = default(int);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLotteryResponse")]
  public partial class PBLotteryResponse
  {
    public PBLotteryResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBLotteryData : data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBLotteryData data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : items
    [global::ProtoBuf.ProtoMember(2, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> items = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ELotteryRollType")]
    public enum ELotteryRollType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"One", Value=0)]
      One = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ten", Value=1)]
      Ten = 1
    }
  
}