//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_campaign.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampaignUnlockDataRequest")]
  public partial class PBCampaignUnlockDataRequest
  {
    public PBCampaignUnlockDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampaignUnlockDataResponse")]
  public partial class PBCampaignUnlockDataResponse
  {
    public PBCampaignUnlockDataResponse() {}
    
    // TYPE_UINT32 : chapter_ids
    [global::ProtoBuf.ProtoMember(1, Name=@"chapter_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> chapter_ids = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllCampaignDataRequest")]
  public partial class PBAllCampaignDataRequest
  {
    public PBAllCampaignDataRequest() {}
    
    // TYPE_UINT32 : chapter_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chapter_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint chapter_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllCampaignDataResponse")]
  public partial class PBAllCampaignDataResponse
  {
    public PBAllCampaignDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBCampaignData : campaigns
    [global::ProtoBuf.ProtoMember(1, Name=@"campaigns", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBCampaignData> campaigns = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBCampaignData>();
  
    // TYPE_UINT32 : chapter_id
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chapter_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint chapter_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBStartFightRequest")]
  public partial class PBStartFightRequest
  {
    public PBStartFightRequest() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBStartFightResponse")]
  public partial class PBStartFightResponse
  {
    public PBStartFightResponse() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : data
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : boss_data
    [global::ProtoBuf.ProtoMember(3, Name=@"boss_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> boss_data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
    // TYPE_INT32 : drop_seed
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"drop_seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int drop_seed = default(int);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampaignFinishRequest")]
  public partial class PBCampaignFinishRequest
  {
    public PBCampaignFinishRequest() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
    // TYPE_UINT32 : fightresult
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fightresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint fightresult = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampaignFinishResponse")]
  public partial class PBCampaignFinishResponse
  {
    public PBCampaignFinishResponse() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBReceiveRewardRequest")]
  public partial class PBReceiveRewardRequest
  {
    public PBReceiveRewardRequest() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBReceiveRewardResponse")]
  public partial class PBReceiveRewardResponse
  {
    public PBReceiveRewardResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : data
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : boss_data
    [global::ProtoBuf.ProtoMember(2, Name=@"boss_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> boss_data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBReviveRequest")]
  public partial class PBReviveRequest
  {
    public PBReviveRequest() {}
    
    // TYPE_UINT32 : campaign_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"campaign_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint campaign_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBReviveResponse")]
  public partial class PBReviveResponse
  {
    public PBReviveResponse() {}
    
  }
  
}