//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_achievement.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGetAllAchievementRequest")]
  public partial class PBGetAllAchievementRequest
  {
    public PBGetAllAchievementRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGetAllAchievementResponse")]
  public partial class PBGetAllAchievementResponse
  {
    public PBGetAllAchievementResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBAchievementData : achievementData
    [global::ProtoBuf.ProtoMember(1, Name=@"achievementData", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBAchievementData> achievementData = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBAchievementData>();
  
  }
  
}