//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_title.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBReceiveTitleRewardRequest")]
  public partial class PBReceiveTitleRewardRequest
  {
    public PBReceiveTitleRewardRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBReceiveTitleRewardResponse")]
  public partial class PBReceiveTitleRewardResponse
  {
    public PBReceiveTitleRewardResponse() {}
    
    // TYPE_UINT32 : titleLevel
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"titleLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint titleLevel = default(uint);
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : rewardData
    [global::ProtoBuf.ProtoMember(2, Name=@"rewardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> rewardData = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
  }
  
}