//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_task.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGetAllTaskDataRequest")]
  public partial class PBGetAllTaskDataRequest
  {
    public PBGetAllTaskDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGetAllTaskDataResponse")]
  public partial class PBGetAllTaskDataResponse
  {
    public PBGetAllTaskDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBTaskDataList : tasks
    [global::ProtoBuf.ProtoMember(1, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBTaskDataList> tasks = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBTaskDataList>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAcceptTaskRequest")]
  public partial class PBAcceptTaskRequest
  {
    public PBAcceptTaskRequest() {}
    
    // TYPE_UINT32 : task_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint task_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAcceptTaskResponse")]
  public partial class PBAcceptTaskResponse
  {
    public PBAcceptTaskResponse() {}
    
    // TYPE_UINT32 : task_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint task_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBFinishTaskRequest")]
  public partial class PBFinishTaskRequest
  {
    public PBFinishTaskRequest() {}
    
    // TYPE_UINT32 : task_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint task_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBFinishTaskResponse")]
  public partial class PBFinishTaskResponse
  {
    public PBFinishTaskResponse() {}
    
    // TYPE_UINT32 : task_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint task_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGainTaskRewardRequest")]
  public partial class PBGainTaskRewardRequest
  {
    public PBGainTaskRewardRequest() {}
    
    // TYPE_UINT32 : task_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint task_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGainTaskRewardResponse")]
  public partial class PBGainTaskRewardResponse
  {
    public PBGainTaskRewardResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBTaskData : task_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBTaskData task_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : reward_data
    [global::ProtoBuf.ProtoMember(2, Name=@"reward_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> reward_data = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
  }
  
}