//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_msg_building.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
// Note: requires additional types generated from: enum_define.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllBuildingDataRequest")]
  public partial class PBAllBuildingDataRequest
  {
    public PBAllBuildingDataRequest() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAllBuildingDataResponse")]
  public partial class PBAllBuildingDataResponse
  {
    public PBAllBuildingDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : buildings
    [global::ProtoBuf.ProtoMember(1, Name=@"buildings", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBBuildingData> buildings = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBBuildingData>();
  
    // TYPE_UINT32 : area_list
    [global::ProtoBuf.ProtoMember(2, Name=@"area_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> area_list = new global::System.Collections.Generic.List<uint>();
  
    // TYPE_UINT32 : unlocked_camp_products
    [global::ProtoBuf.ProtoMember(3, Name=@"unlocked_camp_products", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> unlocked_camp_products = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingBuildRequest")]
  public partial class PBBuildingBuildRequest
  {
    public PBBuildingBuildRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
    // TYPE_BOOL : use_diamond
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"use_diamond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool use_diamond = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingBuildResponse")]
  public partial class PBBuildingBuildResponse
  {
    public PBBuildingBuildResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingUpgradeRequest")]
  public partial class PBBuildingUpgradeRequest
  {
    public PBBuildingUpgradeRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
    // TYPE_BOOL : use_diamond
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"use_diamond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool use_diamond = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingUpgradeResponse")]
  public partial class PBBuildingUpgradeResponse
  {
    public PBBuildingUpgradeResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingSpeedupRequest")]
  public partial class PBBuildingSpeedupRequest
  {
    public PBBuildingSpeedupRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
    // TYPE_BOOL : use_diamond
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"use_diamond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool use_diamond = default(bool);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingSpeedupResponse")]
  public partial class PBBuildingSpeedupResponse
  {
    public PBBuildingSpeedupResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingResCollectRequest")]
  public partial class PBBuildingResCollectRequest
  {
    public PBBuildingResCollectRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingResCollectResponse")]
  public partial class PBBuildingResCollectResponse
  {
    public PBBuildingResCollectResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : gain
    [global::ProtoBuf.ProtoMember(2, Name=@"gain", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> gain = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingSyncDataRequest")]
  public partial class PBBuildingSyncDataRequest
  {
    public PBBuildingSyncDataRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingSyncDataResponse")]
  public partial class PBBuildingSyncDataResponse
  {
    public PBBuildingSyncDataResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingAreaUnlockRequest")]
  public partial class PBBuildingAreaUnlockRequest
  {
    public PBBuildingAreaUnlockRequest() {}
    
    // TYPE_UINT32 : area_id
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint area_id = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingAreaUnlockResponse")]
  public partial class PBBuildingAreaUnlockResponse
  {
    public PBBuildingAreaUnlockResponse() {}
    
    // TYPE_UINT32 : area_list
    [global::ProtoBuf.ProtoMember(1, Name=@"area_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> area_list = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingCampTrainRequest")]
  public partial class PBBuildingCampTrainRequest
  {
    public PBBuildingCampTrainRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
    // TYPE_UINT32 : product_id
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"product_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint product_id = default(uint);
  
    // TYPE_INT32 : product_num
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"product_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int product_num = default(int);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingCampTrainResponse")]
  public partial class PBBuildingCampTrainResponse
  {
    public PBBuildingCampTrainResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingCampCollectRequest")]
  public partial class PBBuildingCampCollectRequest
  {
    public PBBuildingCampCollectRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
    // TYPE_UINT32 : product_id
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"product_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint product_id = default(uint);
  
    // TYPE_INT32 : product_num
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"product_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int product_num = default(int);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBuildingCampCollectResponse")]
  public partial class PBBuildingCampCollectResponse
  {
    public PBBuildingCampCollectResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemValue : items
    [global::ProtoBuf.ProtoMember(2, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue> items = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampTrainNumChgRequest")]
  public partial class PBCampTrainNumChgRequest
  {
    public PBCampTrainNumChgRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
    // TYPE_UINT32 : product_id
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"product_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint product_id = default(uint);
  
    // TYPE_INT32 : num_change
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num_change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int num_change = default(int);
  
    // TYPE_INT32 : num_final
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"num_final", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
	public int num_final = default(int);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampTrainNumChgResponse")]
  public partial class PBCampTrainNumChgResponse
  {
    public PBCampTrainNumChgResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampTrainSkipRequest")]
  public partial class PBCampTrainSkipRequest
  {
    public PBCampTrainSkipRequest() {}
    
    // TYPE_UINT32 : pos
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint pos = default(uint);
  
    // TYPE_UINT32 : bid
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
	public uint bid = default(uint);
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCampTrainSkipResponse")]
  public partial class PBCampTrainSkipResponse
  {
    public PBCampTrainSkipResponse() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBBuildingData : building_data
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBBuildingData building_data = null;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : cost
    [global::ProtoBuf.ProtoMember(2, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> cost = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
}