//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sc_push_msg.proto
// Note: requires additional types generated from: msg_base.proto
// Note: requires additional types generated from: msg_common.proto
// Note: requires additional types generated from: enum_define.proto
namespace FunPlus.Common.Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPlayerResourceSyncPush")]
  public partial class PBPlayerResourceSyncPush
  {
    public PBPlayerResourceSyncPush() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBResourceValue : resources
    [global::ProtoBuf.ProtoMember(1, Name=@"resources", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue> resources = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBResourceValue>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPlayerGainHeroCardPush")]
  public partial class PBPlayerGainHeroCardPush
  {
    public PBPlayerGainHeroCardPush() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBHeroCardData : heroes
    [global::ProtoBuf.ProtoMember(1, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroCardData> heroes = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBHeroCardData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBUnlockedCampProductPush")]
  public partial class PBUnlockedCampProductPush
  {
    public PBUnlockedCampProductPush() {}
    
    // TYPE_UINT32 : unlocked_camp_products
    [global::ProtoBuf.ProtoMember(1, Name=@"unlocked_camp_products", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> unlocked_camp_products = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBUnlockedDungeonPush")]
  public partial class PBUnlockedDungeonPush
  {
    public PBUnlockedDungeonPush() {}
    
    // TYPE_UINT32 : chapter_ids
    [global::ProtoBuf.ProtoMember(1, Name=@"chapter_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
	public readonly global::System.Collections.Generic.List<uint> chapter_ids = new global::System.Collections.Generic.List<uint>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPlayerItemSyncPush")]
  public partial class PBPlayerItemSyncPush
  {
    public PBPlayerItemSyncPush() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBItemData : items
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemData> items = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBItemData>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBDebugLogPush")]
  public partial class PBDebugLogPush
  {
    public PBDebugLogPush() {}
    
    // TYPE_STRING : log
    [global::ProtoBuf.ProtoMember(1, Name=@"log", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<string> log = new global::System.Collections.Generic.List<string>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBTaskPush")]
  public partial class PBTaskPush
  {
    public PBTaskPush() {}
    
    // TYPE_BOOL : is_remove
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_remove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
	public bool is_remove = default(bool);
  
    // TYPE_ENUM.FunPlus.Common.Config.ESTaskStatus : task_status
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"task_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FunPlus.Common.Config.ESTaskStatus.TaskStatus_Inactive)]
	public FunPlus.Common.Config.ESTaskStatus task_status = FunPlus.Common.Config.ESTaskStatus.TaskStatus_Inactive;
  
    // TYPE_MESSAGE.FunPlus.Common.Config.PBTaskData : task_data
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"task_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
	public FunPlus.Common.Config.PBTaskData task_data = null;
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPlayerTaskPush")]
  public partial class PBPlayerTaskPush
  {
    public PBPlayerTaskPush() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBTaskPush : data_list
    [global::ProtoBuf.ProtoMember(1, Name=@"data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBTaskPush> data_list = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBTaskPush>();
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBAchievementDataPush")]
  public partial class PBAchievementDataPush
  {
    public PBAchievementDataPush() {}
    
    // TYPE_MESSAGE.FunPlus.Common.Config.PBAchievementData : achievementData
    [global::ProtoBuf.ProtoMember(1, Name=@"achievementData", DataFormat = global::ProtoBuf.DataFormat.Default)]
	public readonly global::System.Collections.Generic.List<FunPlus.Common.Config.PBAchievementData> achievementData = new global::System.Collections.Generic.List<FunPlus.Common.Config.PBAchievementData>();
  
  }
  
}