// Code generated by protoc-gen-go. DO NOT EDIT.
// source: level_list.proto

package matchproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EFolderType int32

const (
	EFolderType_E_Folder_Designer EFolderType = 0
	EFolderType_E_Folder_Main     EFolderType = 1
	EFolderType_E_Folder_Test     EFolderType = 2
)

var EFolderType_name = map[int32]string{
	0: "E_Folder_Designer",
	1: "E_Folder_Main",
	2: "E_Folder_Test",
}

var EFolderType_value = map[string]int32{
	"E_Folder_Designer": 0,
	"E_Folder_Main":     1,
	"E_Folder_Test":     2,
}

func (x EFolderType) Enum() *EFolderType {
	p := new(EFolderType)
	*p = x
	return p
}

func (x EFolderType) String() string {
	return proto.EnumName(EFolderType_name, int32(x))
}

func (x *EFolderType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EFolderType_value, data, "EFolderType")
	if err != nil {
		return err
	}
	*x = EFolderType(value)
	return nil
}

func (EFolderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{0}
}

type ERole int32

const (
	ERole_Guest    ERole = 0
	ERole_Designer ERole = 1
	ERole_Admin    ERole = 2
)

var ERole_name = map[int32]string{
	0: "Guest",
	1: "Designer",
	2: "Admin",
}

var ERole_value = map[string]int32{
	"Guest":    0,
	"Designer": 1,
	"Admin":    2,
}

func (x ERole) Enum() *ERole {
	p := new(ERole)
	*p = x
	return p
}

func (x ERole) String() string {
	return proto.EnumName(ERole_name, int32(x))
}

func (x *ERole) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ERole_value, data, "ERole")
	if err != nil {
		return err
	}
	*x = ERole(value)
	return nil
}

func (ERole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{1}
}

type ELevelType int32

const (
	ELevelType_E_Main     ELevelType = 0
	ELevelType_E_Activity ELevelType = 1
	ELevelType_E_Week     ELevelType = 2
)

var ELevelType_name = map[int32]string{
	0: "E_Main",
	1: "E_Activity",
	2: "E_Week",
}

var ELevelType_value = map[string]int32{
	"E_Main":     0,
	"E_Activity": 1,
	"E_Week":     2,
}

func (x ELevelType) Enum() *ELevelType {
	p := new(ELevelType)
	*p = x
	return p
}

func (x ELevelType) String() string {
	return proto.EnumName(ELevelType_name, int32(x))
}

func (x *ELevelType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ELevelType_value, data, "ELevelType")
	if err != nil {
		return err
	}
	*x = ELevelType(value)
	return nil
}

func (ELevelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{2}
}

type EVerifyType int32

const (
	EVerifyType_E_Verify_Create EVerifyType = 0
	EVerifyType_E_Verify_Move   EVerifyType = 1
	EVerifyType_E_Verify_Copy   EVerifyType = 2
	EVerifyType_E_Verify_Lock   EVerifyType = 3
)

var EVerifyType_name = map[int32]string{
	0: "E_Verify_Create",
	1: "E_Verify_Move",
	2: "E_Verify_Copy",
	3: "E_Verify_Lock",
}

var EVerifyType_value = map[string]int32{
	"E_Verify_Create": 0,
	"E_Verify_Move":   1,
	"E_Verify_Copy":   2,
	"E_Verify_Lock":   3,
}

func (x EVerifyType) Enum() *EVerifyType {
	p := new(EVerifyType)
	*p = x
	return p
}

func (x EVerifyType) String() string {
	return proto.EnumName(EVerifyType_name, int32(x))
}

func (x *EVerifyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EVerifyType_value, data, "EVerifyType")
	if err != nil {
		return err
	}
	*x = EVerifyType(value)
	return nil
}

func (EVerifyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{3}
}

// 关卡列表
type PBLevelList struct {
	Levels               []*PBLevelDetail `protobuf:"bytes,1,rep,name=levels" json:"levels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBLevelList) Reset()         { *m = PBLevelList{} }
func (m *PBLevelList) String() string { return proto.CompactTextString(m) }
func (*PBLevelList) ProtoMessage()    {}
func (*PBLevelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{0}
}

func (m *PBLevelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBLevelList.Unmarshal(m, b)
}
func (m *PBLevelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBLevelList.Marshal(b, m, deterministic)
}
func (m *PBLevelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBLevelList.Merge(m, src)
}
func (m *PBLevelList) XXX_Size() int {
	return xxx_messageInfo_PBLevelList.Size(m)
}
func (m *PBLevelList) XXX_DiscardUnknown() {
	xxx_messageInfo_PBLevelList.DiscardUnknown(m)
}

var xxx_messageInfo_PBLevelList proto.InternalMessageInfo

func (m *PBLevelList) GetLevels() []*PBLevelDetail {
	if m != nil {
		return m.Levels
	}
	return nil
}

type PBLevelDetail struct {
	ListId               *uint32  `protobuf:"varint,1,opt,name=list_id,json=listId" json:"list_id,omitempty"`
	LevelId              *string  `protobuf:"bytes,2,opt,name=LevelId,json=levelId" json:"LevelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBLevelDetail) Reset()         { *m = PBLevelDetail{} }
func (m *PBLevelDetail) String() string { return proto.CompactTextString(m) }
func (*PBLevelDetail) ProtoMessage()    {}
func (*PBLevelDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{1}
}

func (m *PBLevelDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBLevelDetail.Unmarshal(m, b)
}
func (m *PBLevelDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBLevelDetail.Marshal(b, m, deterministic)
}
func (m *PBLevelDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBLevelDetail.Merge(m, src)
}
func (m *PBLevelDetail) XXX_Size() int {
	return xxx_messageInfo_PBLevelDetail.Size(m)
}
func (m *PBLevelDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PBLevelDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PBLevelDetail proto.InternalMessageInfo

func (m *PBLevelDetail) GetListId() uint32 {
	if m != nil && m.ListId != nil {
		return *m.ListId
	}
	return 0
}

func (m *PBLevelDetail) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

type PBM3FolderList struct {
	Folders              []*PBM3Folder `protobuf:"bytes,1,rep,name=folders" json:"folders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PBM3FolderList) Reset()         { *m = PBM3FolderList{} }
func (m *PBM3FolderList) String() string { return proto.CompactTextString(m) }
func (*PBM3FolderList) ProtoMessage()    {}
func (*PBM3FolderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{2}
}

func (m *PBM3FolderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3FolderList.Unmarshal(m, b)
}
func (m *PBM3FolderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3FolderList.Marshal(b, m, deterministic)
}
func (m *PBM3FolderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3FolderList.Merge(m, src)
}
func (m *PBM3FolderList) XXX_Size() int {
	return xxx_messageInfo_PBM3FolderList.Size(m)
}
func (m *PBM3FolderList) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3FolderList.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3FolderList proto.InternalMessageInfo

func (m *PBM3FolderList) GetFolders() []*PBM3Folder {
	if m != nil {
		return m.Folders
	}
	return nil
}

type PBM3Folder struct {
	Name                 *string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Dir                  *string               `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelDescList        []*PBLevelDescription `protobuf:"bytes,3,rep,name=level_desc_list,json=levelDescList" json:"level_desc_list,omitempty"`
	FolderType           *EFolderType          `protobuf:"varint,4,opt,name=folder_type,json=folderType,enum=FunPlus.Common.Config.EFolderType,def=0" json:"folder_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PBM3Folder) Reset()         { *m = PBM3Folder{} }
func (m *PBM3Folder) String() string { return proto.CompactTextString(m) }
func (*PBM3Folder) ProtoMessage()    {}
func (*PBM3Folder) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{3}
}

func (m *PBM3Folder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3Folder.Unmarshal(m, b)
}
func (m *PBM3Folder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3Folder.Marshal(b, m, deterministic)
}
func (m *PBM3Folder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3Folder.Merge(m, src)
}
func (m *PBM3Folder) XXX_Size() int {
	return xxx_messageInfo_PBM3Folder.Size(m)
}
func (m *PBM3Folder) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3Folder.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3Folder proto.InternalMessageInfo

const Default_PBM3Folder_FolderType EFolderType = EFolderType_E_Folder_Designer

func (m *PBM3Folder) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PBM3Folder) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3Folder) GetLevelDescList() []*PBLevelDescription {
	if m != nil {
		return m.LevelDescList
	}
	return nil
}

func (m *PBM3Folder) GetFolderType() EFolderType {
	if m != nil && m.FolderType != nil {
		return *m.FolderType
	}
	return Default_PBM3Folder_FolderType
}

type PBChipCnt struct {
	ChipId               *uint32  `protobuf:"varint,1,opt,name=chip_id,json=chipId" json:"chip_id,omitempty"`
	Cnt                  *int32   `protobuf:"varint,2,opt,name=cnt" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBChipCnt) Reset()         { *m = PBChipCnt{} }
func (m *PBChipCnt) String() string { return proto.CompactTextString(m) }
func (*PBChipCnt) ProtoMessage()    {}
func (*PBChipCnt) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{4}
}

func (m *PBChipCnt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBChipCnt.Unmarshal(m, b)
}
func (m *PBChipCnt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBChipCnt.Marshal(b, m, deterministic)
}
func (m *PBChipCnt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBChipCnt.Merge(m, src)
}
func (m *PBChipCnt) XXX_Size() int {
	return xxx_messageInfo_PBChipCnt.Size(m)
}
func (m *PBChipCnt) XXX_DiscardUnknown() {
	xxx_messageInfo_PBChipCnt.DiscardUnknown(m)
}

var xxx_messageInfo_PBChipCnt proto.InternalMessageInfo

func (m *PBChipCnt) GetChipId() uint32 {
	if m != nil && m.ChipId != nil {
		return *m.ChipId
	}
	return 0
}

func (m *PBChipCnt) GetCnt() int32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

type PBLevelDescription struct {
	Title                *string      `protobuf:"bytes,1,opt,name=Title,json=title" json:"Title,omitempty"`
	LevelType            *ELevelType  `protobuf:"varint,2,opt,name=LevelType,json=levelType,enum=FunPlus.Common.Config.ELevelType,def=0" json:"LevelType,omitempty"`
	Desc                 *string      `protobuf:"bytes,3,opt,name=Desc,json=desc" json:"Desc,omitempty"`
	Creator              *string      `protobuf:"bytes,4,opt,name=Creator,json=creator" json:"Creator,omitempty"`
	CreateTime           *uint32      `protobuf:"varint,5,opt,name=CreateTime,json=createTime" json:"CreateTime,omitempty"`
	Modifier             *string      `protobuf:"bytes,6,opt,name=Modifier,json=modifier" json:"Modifier,omitempty"`
	ModifyTime           *uint32      `protobuf:"varint,7,opt,name=ModifyTime,json=modifyTime" json:"ModifyTime,omitempty"`
	Lock                 *string      `protobuf:"bytes,8,opt,name=Lock,json=lock" json:"Lock,omitempty"`
	Md5                  *string      `protobuf:"bytes,9,opt,name=Md5,json=md5" json:"Md5,omitempty"`
	LevelId              *string      `protobuf:"bytes,10,opt,name=LevelId,json=levelId" json:"LevelId,omitempty"`
	Order                *int32       `protobuf:"varint,11,opt,name=Order,json=order" json:"Order,omitempty"`
	SyncTag              *bool        `protobuf:"varint,12,opt,name=sync_tag,json=syncTag,def=0" json:"sync_tag,omitempty"`
	ChipsCnt             []*PBChipCnt `protobuf:"bytes,13,rep,name=chips_cnt,json=chipsCnt" json:"chips_cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PBLevelDescription) Reset()         { *m = PBLevelDescription{} }
func (m *PBLevelDescription) String() string { return proto.CompactTextString(m) }
func (*PBLevelDescription) ProtoMessage()    {}
func (*PBLevelDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_65f3409998e907dc, []int{5}
}

func (m *PBLevelDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBLevelDescription.Unmarshal(m, b)
}
func (m *PBLevelDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBLevelDescription.Marshal(b, m, deterministic)
}
func (m *PBLevelDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBLevelDescription.Merge(m, src)
}
func (m *PBLevelDescription) XXX_Size() int {
	return xxx_messageInfo_PBLevelDescription.Size(m)
}
func (m *PBLevelDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_PBLevelDescription.DiscardUnknown(m)
}

var xxx_messageInfo_PBLevelDescription proto.InternalMessageInfo

const Default_PBLevelDescription_LevelType ELevelType = ELevelType_E_Main
const Default_PBLevelDescription_SyncTag bool = false

func (m *PBLevelDescription) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PBLevelDescription) GetLevelType() ELevelType {
	if m != nil && m.LevelType != nil {
		return *m.LevelType
	}
	return Default_PBLevelDescription_LevelType
}

func (m *PBLevelDescription) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *PBLevelDescription) GetCreator() string {
	if m != nil && m.Creator != nil {
		return *m.Creator
	}
	return ""
}

func (m *PBLevelDescription) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *PBLevelDescription) GetModifier() string {
	if m != nil && m.Modifier != nil {
		return *m.Modifier
	}
	return ""
}

func (m *PBLevelDescription) GetModifyTime() uint32 {
	if m != nil && m.ModifyTime != nil {
		return *m.ModifyTime
	}
	return 0
}

func (m *PBLevelDescription) GetLock() string {
	if m != nil && m.Lock != nil {
		return *m.Lock
	}
	return ""
}

func (m *PBLevelDescription) GetMd5() string {
	if m != nil && m.Md5 != nil {
		return *m.Md5
	}
	return ""
}

func (m *PBLevelDescription) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

func (m *PBLevelDescription) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

func (m *PBLevelDescription) GetSyncTag() bool {
	if m != nil && m.SyncTag != nil {
		return *m.SyncTag
	}
	return Default_PBLevelDescription_SyncTag
}

func (m *PBLevelDescription) GetChipsCnt() []*PBChipCnt {
	if m != nil {
		return m.ChipsCnt
	}
	return nil
}

func init() {
	proto.RegisterEnum("FunPlus.Common.Config.EFolderType", EFolderType_name, EFolderType_value)
	proto.RegisterEnum("FunPlus.Common.Config.ERole", ERole_name, ERole_value)
	proto.RegisterEnum("FunPlus.Common.Config.ELevelType", ELevelType_name, ELevelType_value)
	proto.RegisterEnum("FunPlus.Common.Config.EVerifyType", EVerifyType_name, EVerifyType_value)
	proto.RegisterType((*PBLevelList)(nil), "FunPlus.Common.Config.PBLevelList")
	proto.RegisterType((*PBLevelDetail)(nil), "FunPlus.Common.Config.PBLevelDetail")
	proto.RegisterType((*PBM3FolderList)(nil), "FunPlus.Common.Config.PBM3FolderList")
	proto.RegisterType((*PBM3Folder)(nil), "FunPlus.Common.Config.PBM3Folder")
	proto.RegisterType((*PBChipCnt)(nil), "FunPlus.Common.Config.PBChipCnt")
	proto.RegisterType((*PBLevelDescription)(nil), "FunPlus.Common.Config.PBLevelDescription")
}

func init() { proto.RegisterFile("level_list.proto", fileDescriptor_65f3409998e907dc) }

var fileDescriptor_65f3409998e907dc = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xad, 0x93, 0x3a, 0xb6, 0x27, 0x4d, 0xea, 0xee, 0xf7, 0x55, 0x58, 0x1c, 0x90, 0xb1, 0x38,
	0x84, 0x20, 0xe5, 0x50, 0x28, 0x87, 0x02, 0x87, 0x26, 0x75, 0xab, 0x42, 0x23, 0x82, 0x15, 0x15,
	0x09, 0x0e, 0x96, 0x65, 0x6f, 0xd2, 0x55, 0x6d, 0xaf, 0x65, 0x6f, 0x2b, 0xe5, 0x7f, 0xf1, 0x77,
	0xf8, 0x2f, 0x68, 0x76, 0xed, 0xb4, 0x51, 0x89, 0xb8, 0xf9, 0xbd, 0x99, 0xb7, 0xfb, 0xf6, 0xcd,
	0xc8, 0x60, 0xa7, 0xf4, 0x9e, 0xa6, 0x61, 0xca, 0x2a, 0x31, 0x2a, 0x4a, 0x2e, 0x38, 0x39, 0x3c,
	0xbf, 0xcb, 0x67, 0xe9, 0x5d, 0x35, 0x9a, 0xf0, 0x2c, 0xe3, 0xf9, 0x68, 0xc2, 0xf3, 0x05, 0x5b,
	0x7a, 0x5f, 0xa0, 0x3b, 0x1b, 0x5f, 0x61, 0xf3, 0x15, 0xab, 0x04, 0xf9, 0x08, 0x1d, 0xa9, 0xac,
	0x1c, 0xcd, 0x6d, 0x0f, 0xba, 0x47, 0xaf, 0x46, 0x7f, 0x95, 0x8d, 0x6a, 0xcd, 0x19, 0x15, 0x11,
	0x4b, 0x83, 0x5a, 0xe3, 0x8d, 0xa1, 0xb7, 0x51, 0x20, 0xcf, 0xc0, 0x40, 0x0b, 0x21, 0x4b, 0x1c,
	0xcd, 0xd5, 0x06, 0xbd, 0xa0, 0x83, 0xf0, 0x32, 0x21, 0x0e, 0x18, 0xb2, 0xef, 0x32, 0x71, 0x5a,
	0xae, 0x36, 0xb0, 0x02, 0x23, 0x55, 0xd0, 0x9b, 0x42, 0x7f, 0x36, 0x9e, 0xbe, 0x3d, 0xe7, 0x69,
	0x42, 0x4b, 0xe9, 0xe9, 0x03, 0x18, 0x0b, 0x89, 0x1a, 0x53, 0x2f, 0xb7, 0x9a, 0x6a, 0x74, 0x41,
	0xa3, 0xf0, 0x7e, 0x6b, 0x00, 0x0f, 0x3c, 0x21, 0xb0, 0x9b, 0x47, 0x19, 0x95, 0x6e, 0xac, 0x40,
	0x7e, 0x13, 0x1b, 0xda, 0x09, 0x2b, 0x6b, 0x1f, 0xf8, 0x49, 0xbe, 0xc1, 0xbe, 0xca, 0x2f, 0xa1,
	0x55, 0x2c, 0x43, 0x74, 0xda, 0xf2, 0xe6, 0xd7, 0xff, 0x8a, 0xa3, 0x8a, 0x4b, 0x56, 0x08, 0xc6,
	0xf3, 0xa0, 0x97, 0x36, 0x8c, 0x7c, 0xc4, 0x35, 0x74, 0x95, 0xa5, 0x50, 0xac, 0x0a, 0xea, 0xec,
	0xba, 0xda, 0xa0, 0x7f, 0xe4, 0x6d, 0x39, 0xce, 0x57, 0x6e, 0xe7, 0xab, 0x82, 0x9e, 0x1c, 0xf8,
	0xa1, 0x42, 0xe1, 0x19, 0xad, 0xd8, 0x32, 0xa7, 0x65, 0x00, 0x8b, 0x75, 0xd9, 0x7b, 0x0f, 0xd6,
	0x6c, 0x3c, 0xb9, 0x61, 0xc5, 0x24, 0x17, 0x18, 0x77, 0x7c, 0xc3, 0x8a, 0x47, 0x71, 0x23, 0xbc,
	0x4c, 0xf0, 0x89, 0x71, 0x2e, 0xe4, 0x13, 0xf5, 0x00, 0x3f, 0xbd, 0x5f, 0x6d, 0x20, 0x4f, 0x5d,
	0x93, 0xff, 0x41, 0x9f, 0x33, 0x91, 0x36, 0x01, 0xe9, 0x02, 0x01, 0xb9, 0x00, 0x4b, 0x76, 0xe2,
	0x8d, 0xf2, 0x90, 0xfe, 0xd6, 0x19, 0xf8, 0xeb, 0xc6, 0x93, 0x8e, 0x1f, 0x4e, 0x23, 0x96, 0x07,
	0x56, 0xda, 0x50, 0x18, 0x3f, 0xde, 0xe6, 0xb4, 0x55, 0xfc, 0x18, 0x2f, 0xae, 0xc2, 0xa4, 0xa4,
	0x91, 0xe0, 0xa5, 0x4c, 0xc5, 0x0a, 0x8c, 0x58, 0x41, 0xf2, 0x02, 0x40, 0x56, 0xe8, 0x9c, 0x65,
	0xd4, 0xd1, 0xe5, 0x8b, 0x20, 0x5e, 0x33, 0xe4, 0x39, 0x98, 0x53, 0x9e, 0xb0, 0x05, 0xa3, 0xa5,
	0xd3, 0x91, 0x52, 0x33, 0xab, 0x31, 0x6a, 0x65, 0x6d, 0x25, 0xb5, 0x86, 0xd2, 0x66, 0x6b, 0x06,
	0x9d, 0x5c, 0xf1, 0xf8, 0xd6, 0x31, 0x95, 0x93, 0x94, 0xc7, 0xb7, 0x98, 0xd2, 0x34, 0x39, 0x76,
	0x2c, 0xb5, 0x08, 0x59, 0x72, 0xfc, 0x78, 0x4d, 0x61, 0x63, 0x4d, 0x31, 0xa8, 0xaf, 0x65, 0x42,
	0x4b, 0xa7, 0x2b, 0x33, 0xd5, 0x39, 0x02, 0xe2, 0x82, 0x59, 0xad, 0xf2, 0x38, 0x14, 0xd1, 0xd2,
	0xd9, 0x73, 0xb5, 0x81, 0x79, 0xa2, 0x2f, 0xa2, 0xb4, 0xa2, 0x81, 0x81, 0xf4, 0x3c, 0x5a, 0x92,
	0x4f, 0x60, 0xe1, 0x4c, 0xaa, 0x10, 0xe7, 0xd1, 0x93, 0x4b, 0xe5, 0x6e, 0x5d, 0xaa, 0x7a, 0xae,
	0x81, 0x29, 0x25, 0x93, 0x5c, 0x0c, 0x3f, 0x43, 0xf7, 0xd1, 0x72, 0x90, 0x43, 0x78, 0xba, 0x1e,
	0xf6, 0x0e, 0x39, 0x80, 0xde, 0x9a, 0xc6, 0x11, 0xd8, 0xda, 0x06, 0x35, 0xa7, 0x95, 0xb0, 0x5b,
	0xc3, 0x37, 0xa0, 0xfb, 0x01, 0x4f, 0x29, 0xb1, 0x40, 0xbf, 0xb8, 0x43, 0x6e, 0x87, 0xec, 0x81,
	0xb9, 0x3e, 0x47, 0xc3, 0xc2, 0x69, 0x92, 0xb1, 0xdc, 0x6e, 0x0d, 0xdf, 0x01, 0x3c, 0x8c, 0x96,
	0x00, 0xd4, 0xc3, 0xb5, 0x77, 0x48, 0x1f, 0xc0, 0x0f, 0x4f, 0x63, 0xc1, 0xee, 0x99, 0x58, 0xd9,
	0x9a, 0xaa, 0x7d, 0xa7, 0xf4, 0xd6, 0x6e, 0x0d, 0x7f, 0x42, 0xd7, 0xbf, 0xa6, 0x25, 0x86, 0x8e,
	0xb2, 0xff, 0x60, 0xdf, 0x0f, 0x15, 0x0e, 0xd5, 0x64, 0x1b, 0xb3, 0x35, 0x39, 0xe5, 0xf7, 0xb4,
	0x31, 0xdb, 0xf4, 0xf1, 0x62, 0x65, 0xb7, 0x36, 0x28, 0x1c, 0x9c, 0xdd, 0x1e, 0xef, 0xfd, 0x80,
	0x2c, 0x12, 0xf1, 0x8d, 0xfc, 0xbf, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xda, 0xcb, 0x22, 0x3d,
	0xf2, 0x04, 0x00, 0x00,
}
