// Code generated by protoc-gen-go. DO NOT EDIT.
// source: match3_tutorials.proto

package matchproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ETutorialAnimType int32

const (
	ETutorialAnimType_TA_Static ETutorialAnimType = 0
	ETutorialAnimType_TA_Left   ETutorialAnimType = 1
	ETutorialAnimType_TA_Right  ETutorialAnimType = 2
	ETutorialAnimType_TA_Up     ETutorialAnimType = 3
	ETutorialAnimType_TA_Down   ETutorialAnimType = 4
	ETutorialAnimType_TA_Rot    ETutorialAnimType = 5
)

var ETutorialAnimType_name = map[int32]string{
	0: "TA_Static",
	1: "TA_Left",
	2: "TA_Right",
	3: "TA_Up",
	4: "TA_Down",
	5: "TA_Rot",
}

var ETutorialAnimType_value = map[string]int32{
	"TA_Static": 0,
	"TA_Left":   1,
	"TA_Right":  2,
	"TA_Up":     3,
	"TA_Down":   4,
	"TA_Rot":    5,
}

func (x ETutorialAnimType) Enum() *ETutorialAnimType {
	p := new(ETutorialAnimType)
	*p = x
	return p
}

func (x ETutorialAnimType) String() string {
	return proto.EnumName(ETutorialAnimType_name, int32(x))
}

func (x *ETutorialAnimType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETutorialAnimType_value, data, "ETutorialAnimType")
	if err != nil {
		return err
	}
	*x = ETutorialAnimType(value)
	return nil
}

func (ETutorialAnimType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{0}
}

type ETutorialStepFinishType int32

const (
	ETutorialStepFinishType_TS_Move    ETutorialStepFinishType = 0
	ETutorialStepFinishType_TS_Click   ETutorialStepFinishType = 1
	ETutorialStepFinishType_TS_Item    ETutorialStepFinishType = 2
	ETutorialStepFinishType_TS_ItemUse ETutorialStepFinishType = 3
)

var ETutorialStepFinishType_name = map[int32]string{
	0: "TS_Move",
	1: "TS_Click",
	2: "TS_Item",
	3: "TS_ItemUse",
}

var ETutorialStepFinishType_value = map[string]int32{
	"TS_Move":    0,
	"TS_Click":   1,
	"TS_Item":    2,
	"TS_ItemUse": 3,
}

func (x ETutorialStepFinishType) Enum() *ETutorialStepFinishType {
	p := new(ETutorialStepFinishType)
	*p = x
	return p
}

func (x ETutorialStepFinishType) String() string {
	return proto.EnumName(ETutorialStepFinishType_name, int32(x))
}

func (x *ETutorialStepFinishType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETutorialStepFinishType_value, data, "ETutorialStepFinishType")
	if err != nil {
		return err
	}
	*x = ETutorialStepFinishType(value)
	return nil
}

func (ETutorialStepFinishType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{1}
}

type EpointUI int32

const (
	EpointUI_E_None  EpointUI = 0
	EpointUI_E_Step  EpointUI = 1
	EpointUI_E_Item1 EpointUI = 2
	EpointUI_E_Item2 EpointUI = 3
	EpointUI_E_Item3 EpointUI = 4
	EpointUI_E_Goal  EpointUI = 5
)

var EpointUI_name = map[int32]string{
	0: "E_None",
	1: "E_Step",
	2: "E_Item1",
	3: "E_Item2",
	4: "E_Item3",
	5: "E_Goal",
}

var EpointUI_value = map[string]int32{
	"E_None":  0,
	"E_Step":  1,
	"E_Item1": 2,
	"E_Item2": 3,
	"E_Item3": 4,
	"E_Goal":  5,
}

func (x EpointUI) Enum() *EpointUI {
	p := new(EpointUI)
	*p = x
	return p
}

func (x EpointUI) String() string {
	return proto.EnumName(EpointUI_name, int32(x))
}

func (x *EpointUI) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EpointUI_value, data, "EpointUI")
	if err != nil {
		return err
	}
	*x = EpointUI(value)
	return nil
}

func (EpointUI) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{2}
}

type PBTutorial struct {
	Id                   *string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Folder               *string            `protobuf:"bytes,2,opt,name=folder" json:"folder,omitempty"`
	Repeat               *bool              `protobuf:"varint,3,opt,name=repeat" json:"repeat,omitempty"`
	Steps                []*PBTutorialSteps `protobuf:"bytes,4,rep,name=steps" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PBTutorial) Reset()         { *m = PBTutorial{} }
func (m *PBTutorial) String() string { return proto.CompactTextString(m) }
func (*PBTutorial) ProtoMessage()    {}
func (*PBTutorial) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{0}
}

func (m *PBTutorial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTutorial.Unmarshal(m, b)
}
func (m *PBTutorial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTutorial.Marshal(b, m, deterministic)
}
func (m *PBTutorial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTutorial.Merge(m, src)
}
func (m *PBTutorial) XXX_Size() int {
	return xxx_messageInfo_PBTutorial.Size(m)
}
func (m *PBTutorial) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTutorial.DiscardUnknown(m)
}

var xxx_messageInfo_PBTutorial proto.InternalMessageInfo

func (m *PBTutorial) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *PBTutorial) GetFolder() string {
	if m != nil && m.Folder != nil {
		return *m.Folder
	}
	return ""
}

func (m *PBTutorial) GetRepeat() bool {
	if m != nil && m.Repeat != nil {
		return *m.Repeat
	}
	return false
}

func (m *PBTutorial) GetSteps() []*PBTutorialSteps {
	if m != nil {
		return m.Steps
	}
	return nil
}

type PBTutorialDialog struct {
	Duration  *float32 `protobuf:"fixed32,1,opt,name=duration" json:"duration,omitempty"`
	Texture   *string  `protobuf:"bytes,2,opt,name=texture" json:"texture,omitempty"`
	Picture   *string  `protobuf:"bytes,18,opt,name=picture" json:"picture,omitempty"`
	ScaleX    *float32 `protobuf:"fixed32,16,opt,name=scale_x,json=scaleX" json:"scale_x,omitempty"`
	ScaleY    *float32 `protobuf:"fixed32,17,opt,name=scale_y,json=scaleY" json:"scale_y,omitempty"`
	X         *int32   `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y         *int32   `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	Text      *string  `protobuf:"bytes,7,opt,name=text" json:"text,omitempty"`
	TextWidth *int32   `protobuf:"varint,10,opt,name=text_width,json=textWidth" json:"text_width,omitempty"`
	//optional int32 text_height		= 10;
	SmallArrow           *bool    `protobuf:"varint,11,opt,name=small_arrow,json=smallArrow" json:"small_arrow,omitempty"`
	Avatar               *string  `protobuf:"bytes,12,opt,name=avatar" json:"avatar,omitempty"`
	AvatarScale          *float32 `protobuf:"fixed32,13,opt,name=avatar_scale,json=avatarScale" json:"avatar_scale,omitempty"`
	AvatarX              *int32   `protobuf:"varint,14,opt,name=avatar_x,json=avatarX" json:"avatar_x,omitempty"`
	AvatarY              *int32   `protobuf:"varint,15,opt,name=avatar_y,json=avatarY" json:"avatar_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBTutorialDialog) Reset()         { *m = PBTutorialDialog{} }
func (m *PBTutorialDialog) String() string { return proto.CompactTextString(m) }
func (*PBTutorialDialog) ProtoMessage()    {}
func (*PBTutorialDialog) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{1}
}

func (m *PBTutorialDialog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTutorialDialog.Unmarshal(m, b)
}
func (m *PBTutorialDialog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTutorialDialog.Marshal(b, m, deterministic)
}
func (m *PBTutorialDialog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTutorialDialog.Merge(m, src)
}
func (m *PBTutorialDialog) XXX_Size() int {
	return xxx_messageInfo_PBTutorialDialog.Size(m)
}
func (m *PBTutorialDialog) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTutorialDialog.DiscardUnknown(m)
}

var xxx_messageInfo_PBTutorialDialog proto.InternalMessageInfo

func (m *PBTutorialDialog) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *PBTutorialDialog) GetTexture() string {
	if m != nil && m.Texture != nil {
		return *m.Texture
	}
	return ""
}

func (m *PBTutorialDialog) GetPicture() string {
	if m != nil && m.Picture != nil {
		return *m.Picture
	}
	return ""
}

func (m *PBTutorialDialog) GetScaleX() float32 {
	if m != nil && m.ScaleX != nil {
		return *m.ScaleX
	}
	return 0
}

func (m *PBTutorialDialog) GetScaleY() float32 {
	if m != nil && m.ScaleY != nil {
		return *m.ScaleY
	}
	return 0
}

func (m *PBTutorialDialog) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PBTutorialDialog) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PBTutorialDialog) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *PBTutorialDialog) GetTextWidth() int32 {
	if m != nil && m.TextWidth != nil {
		return *m.TextWidth
	}
	return 0
}

func (m *PBTutorialDialog) GetSmallArrow() bool {
	if m != nil && m.SmallArrow != nil {
		return *m.SmallArrow
	}
	return false
}

func (m *PBTutorialDialog) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *PBTutorialDialog) GetAvatarScale() float32 {
	if m != nil && m.AvatarScale != nil {
		return *m.AvatarScale
	}
	return 0
}

func (m *PBTutorialDialog) GetAvatarX() int32 {
	if m != nil && m.AvatarX != nil {
		return *m.AvatarX
	}
	return 0
}

func (m *PBTutorialDialog) GetAvatarY() int32 {
	if m != nil && m.AvatarY != nil {
		return *m.AvatarY
	}
	return 0
}

type PBTutorialArrows struct {
	Scale                *float32  `protobuf:"fixed32,1,opt,name=scale" json:"scale,omitempty"`
	Delay                *float32  `protobuf:"fixed32,2,opt,name=delay" json:"delay,omitempty"`
	Angle                *int32    `protobuf:"varint,3,opt,name=angle" json:"angle,omitempty"`
	OffsetX              *float32  `protobuf:"fixed32,4,opt,name=offset_x,json=offsetX" json:"offset_x,omitempty"`
	OffsetY              *float32  `protobuf:"fixed32,5,opt,name=offset_y,json=offsetY" json:"offset_y,omitempty"`
	IsPointCell          *bool     `protobuf:"varint,6,opt,name=is_point_cell,json=isPointCell" json:"is_point_cell,omitempty"`
	CellX                *int32    `protobuf:"varint,7,opt,name=cell_x,json=cellX" json:"cell_x,omitempty"`
	CellY                *int32    `protobuf:"varint,8,opt,name=cell_y,json=cellY" json:"cell_y,omitempty"`
	UiObj                *string   `protobuf:"bytes,9,opt,name=ui_obj,json=uiObj" json:"ui_obj,omitempty"`
	PointUi              *EpointUI `protobuf:"varint,10,opt,name=point_ui,json=pointUi,enum=FunPlus.Common.Config.EpointUI,def=0" json:"point_ui,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PBTutorialArrows) Reset()         { *m = PBTutorialArrows{} }
func (m *PBTutorialArrows) String() string { return proto.CompactTextString(m) }
func (*PBTutorialArrows) ProtoMessage()    {}
func (*PBTutorialArrows) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{2}
}

func (m *PBTutorialArrows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTutorialArrows.Unmarshal(m, b)
}
func (m *PBTutorialArrows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTutorialArrows.Marshal(b, m, deterministic)
}
func (m *PBTutorialArrows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTutorialArrows.Merge(m, src)
}
func (m *PBTutorialArrows) XXX_Size() int {
	return xxx_messageInfo_PBTutorialArrows.Size(m)
}
func (m *PBTutorialArrows) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTutorialArrows.DiscardUnknown(m)
}

var xxx_messageInfo_PBTutorialArrows proto.InternalMessageInfo

const Default_PBTutorialArrows_PointUi EpointUI = EpointUI_E_None

func (m *PBTutorialArrows) GetScale() float32 {
	if m != nil && m.Scale != nil {
		return *m.Scale
	}
	return 0
}

func (m *PBTutorialArrows) GetDelay() float32 {
	if m != nil && m.Delay != nil {
		return *m.Delay
	}
	return 0
}

func (m *PBTutorialArrows) GetAngle() int32 {
	if m != nil && m.Angle != nil {
		return *m.Angle
	}
	return 0
}

func (m *PBTutorialArrows) GetOffsetX() float32 {
	if m != nil && m.OffsetX != nil {
		return *m.OffsetX
	}
	return 0
}

func (m *PBTutorialArrows) GetOffsetY() float32 {
	if m != nil && m.OffsetY != nil {
		return *m.OffsetY
	}
	return 0
}

func (m *PBTutorialArrows) GetIsPointCell() bool {
	if m != nil && m.IsPointCell != nil {
		return *m.IsPointCell
	}
	return false
}

func (m *PBTutorialArrows) GetCellX() int32 {
	if m != nil && m.CellX != nil {
		return *m.CellX
	}
	return 0
}

func (m *PBTutorialArrows) GetCellY() int32 {
	if m != nil && m.CellY != nil {
		return *m.CellY
	}
	return 0
}

func (m *PBTutorialArrows) GetUiObj() string {
	if m != nil && m.UiObj != nil {
		return *m.UiObj
	}
	return ""
}

func (m *PBTutorialArrows) GetPointUi() EpointUI {
	if m != nil && m.PointUi != nil {
		return *m.PointUi
	}
	return Default_PBTutorialArrows_PointUi
}

type PBTutorialKiteFly struct {
	StartX               *int32   `protobuf:"varint,1,opt,name=start_x,json=startX" json:"start_x,omitempty"`
	StartY               *int32   `protobuf:"varint,2,opt,name=start_y,json=startY" json:"start_y,omitempty"`
	TargetX              *int32   `protobuf:"varint,3,opt,name=target_x,json=targetX" json:"target_x,omitempty"`
	TargetY              *int32   `protobuf:"varint,4,opt,name=target_y,json=targetY" json:"target_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBTutorialKiteFly) Reset()         { *m = PBTutorialKiteFly{} }
func (m *PBTutorialKiteFly) String() string { return proto.CompactTextString(m) }
func (*PBTutorialKiteFly) ProtoMessage()    {}
func (*PBTutorialKiteFly) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{3}
}

func (m *PBTutorialKiteFly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTutorialKiteFly.Unmarshal(m, b)
}
func (m *PBTutorialKiteFly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTutorialKiteFly.Marshal(b, m, deterministic)
}
func (m *PBTutorialKiteFly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTutorialKiteFly.Merge(m, src)
}
func (m *PBTutorialKiteFly) XXX_Size() int {
	return xxx_messageInfo_PBTutorialKiteFly.Size(m)
}
func (m *PBTutorialKiteFly) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTutorialKiteFly.DiscardUnknown(m)
}

var xxx_messageInfo_PBTutorialKiteFly proto.InternalMessageInfo

func (m *PBTutorialKiteFly) GetStartX() int32 {
	if m != nil && m.StartX != nil {
		return *m.StartX
	}
	return 0
}

func (m *PBTutorialKiteFly) GetStartY() int32 {
	if m != nil && m.StartY != nil {
		return *m.StartY
	}
	return 0
}

func (m *PBTutorialKiteFly) GetTargetX() int32 {
	if m != nil && m.TargetX != nil {
		return *m.TargetX
	}
	return 0
}

func (m *PBTutorialKiteFly) GetTargetY() int32 {
	if m != nil && m.TargetY != nil {
		return *m.TargetY
	}
	return 0
}

type PBTutorialCells struct {
	CellX                *int32             `protobuf:"varint,1,opt,name=cell_x,json=cellX" json:"cell_x,omitempty"`
	CellY                *int32             `protobuf:"varint,2,opt,name=cell_y,json=cellY" json:"cell_y,omitempty"`
	AnimType             *ETutorialAnimType `protobuf:"varint,3,opt,name=anim_type,json=animType,enum=FunPlus.Common.Config.ETutorialAnimType,def=0" json:"anim_type,omitempty"`
	Locked               *bool              `protobuf:"varint,4,opt,name=locked" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PBTutorialCells) Reset()         { *m = PBTutorialCells{} }
func (m *PBTutorialCells) String() string { return proto.CompactTextString(m) }
func (*PBTutorialCells) ProtoMessage()    {}
func (*PBTutorialCells) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{4}
}

func (m *PBTutorialCells) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTutorialCells.Unmarshal(m, b)
}
func (m *PBTutorialCells) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTutorialCells.Marshal(b, m, deterministic)
}
func (m *PBTutorialCells) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTutorialCells.Merge(m, src)
}
func (m *PBTutorialCells) XXX_Size() int {
	return xxx_messageInfo_PBTutorialCells.Size(m)
}
func (m *PBTutorialCells) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTutorialCells.DiscardUnknown(m)
}

var xxx_messageInfo_PBTutorialCells proto.InternalMessageInfo

const Default_PBTutorialCells_AnimType ETutorialAnimType = ETutorialAnimType_TA_Static

func (m *PBTutorialCells) GetCellX() int32 {
	if m != nil && m.CellX != nil {
		return *m.CellX
	}
	return 0
}

func (m *PBTutorialCells) GetCellY() int32 {
	if m != nil && m.CellY != nil {
		return *m.CellY
	}
	return 0
}

func (m *PBTutorialCells) GetAnimType() ETutorialAnimType {
	if m != nil && m.AnimType != nil {
		return *m.AnimType
	}
	return Default_PBTutorialCells_AnimType
}

func (m *PBTutorialCells) GetLocked() bool {
	if m != nil && m.Locked != nil {
		return *m.Locked
	}
	return false
}

type PBTutorialSteps struct {
	Index                *uint32                  `protobuf:"varint,8,opt,name=index" json:"index,omitempty"`
	Move                 *uint32                  `protobuf:"varint,1,opt,name=move" json:"move,omitempty"`
	FinishType           *ETutorialStepFinishType `protobuf:"varint,2,opt,name=finish_type,json=finishType,enum=FunPlus.Common.Config.ETutorialStepFinishType,def=0" json:"finish_type,omitempty"`
	Dialog               *PBTutorialDialog        `protobuf:"bytes,3,opt,name=dialog" json:"dialog,omitempty"`
	TapOnBonus           *bool                    `protobuf:"varint,4,opt,name=tap_on_bonus,json=tapOnBonus" json:"tap_on_bonus,omitempty"`
	Arrows               []*PBTutorialArrows      `protobuf:"bytes,5,rep,name=arrows" json:"arrows,omitempty"`
	Kiteflys             []*PBTutorialKiteFly     `protobuf:"bytes,6,rep,name=kiteflys" json:"kiteflys,omitempty"`
	Cells                []*PBTutorialCells       `protobuf:"bytes,7,rep,name=cells" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PBTutorialSteps) Reset()         { *m = PBTutorialSteps{} }
func (m *PBTutorialSteps) String() string { return proto.CompactTextString(m) }
func (*PBTutorialSteps) ProtoMessage()    {}
func (*PBTutorialSteps) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5045fe0b4d17e9, []int{5}
}

func (m *PBTutorialSteps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTutorialSteps.Unmarshal(m, b)
}
func (m *PBTutorialSteps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTutorialSteps.Marshal(b, m, deterministic)
}
func (m *PBTutorialSteps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTutorialSteps.Merge(m, src)
}
func (m *PBTutorialSteps) XXX_Size() int {
	return xxx_messageInfo_PBTutorialSteps.Size(m)
}
func (m *PBTutorialSteps) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTutorialSteps.DiscardUnknown(m)
}

var xxx_messageInfo_PBTutorialSteps proto.InternalMessageInfo

const Default_PBTutorialSteps_FinishType ETutorialStepFinishType = ETutorialStepFinishType_TS_Move

func (m *PBTutorialSteps) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *PBTutorialSteps) GetMove() uint32 {
	if m != nil && m.Move != nil {
		return *m.Move
	}
	return 0
}

func (m *PBTutorialSteps) GetFinishType() ETutorialStepFinishType {
	if m != nil && m.FinishType != nil {
		return *m.FinishType
	}
	return Default_PBTutorialSteps_FinishType
}

func (m *PBTutorialSteps) GetDialog() *PBTutorialDialog {
	if m != nil {
		return m.Dialog
	}
	return nil
}

func (m *PBTutorialSteps) GetTapOnBonus() bool {
	if m != nil && m.TapOnBonus != nil {
		return *m.TapOnBonus
	}
	return false
}

func (m *PBTutorialSteps) GetArrows() []*PBTutorialArrows {
	if m != nil {
		return m.Arrows
	}
	return nil
}

func (m *PBTutorialSteps) GetKiteflys() []*PBTutorialKiteFly {
	if m != nil {
		return m.Kiteflys
	}
	return nil
}

func (m *PBTutorialSteps) GetCells() []*PBTutorialCells {
	if m != nil {
		return m.Cells
	}
	return nil
}

func init() {
	proto.RegisterEnum("FunPlus.Common.Config.ETutorialAnimType", ETutorialAnimType_name, ETutorialAnimType_value)
	proto.RegisterEnum("FunPlus.Common.Config.ETutorialStepFinishType", ETutorialStepFinishType_name, ETutorialStepFinishType_value)
	proto.RegisterEnum("FunPlus.Common.Config.EpointUI", EpointUI_name, EpointUI_value)
	proto.RegisterType((*PBTutorial)(nil), "FunPlus.Common.Config.PBTutorial")
	proto.RegisterType((*PBTutorialDialog)(nil), "FunPlus.Common.Config.PBTutorialDialog")
	proto.RegisterType((*PBTutorialArrows)(nil), "FunPlus.Common.Config.PBTutorialArrows")
	proto.RegisterType((*PBTutorialKiteFly)(nil), "FunPlus.Common.Config.PBTutorialKiteFly")
	proto.RegisterType((*PBTutorialCells)(nil), "FunPlus.Common.Config.PBTutorialCells")
	proto.RegisterType((*PBTutorialSteps)(nil), "FunPlus.Common.Config.PBTutorialSteps")
}

func init() { proto.RegisterFile("match3_tutorials.proto", fileDescriptor_8f5045fe0b4d17e9) }

var fileDescriptor_8f5045fe0b4d17e9 = []byte{
	// 908 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcb, 0x6e, 0xe3, 0x36,
	0x14, 0x1d, 0xc9, 0x91, 0x25, 0x5f, 0x3f, 0x46, 0x21, 0x3a, 0x33, 0x6c, 0x81, 0x62, 0x52, 0x2f,
	0x5a, 0x23, 0x0b, 0x03, 0xf5, 0xec, 0x06, 0x05, 0x0a, 0xe7, 0x55, 0x0c, 0xfa, 0x98, 0x54, 0x76,
	0x50, 0xbb, 0x1b, 0x82, 0xb1, 0x69, 0x87, 0x13, 0x59, 0x14, 0x44, 0x3a, 0xb1, 0xd0, 0x3f, 0xe8,
	0x9f, 0xf4, 0x0b, 0xba, 0xea, 0x67, 0x75, 0x5f, 0xf0, 0x52, 0xb1, 0x5d, 0x74, 0x82, 0x74, 0x65,
	0x9d, 0x73, 0x48, 0xde, 0xc3, 0xc3, 0x4b, 0x1a, 0x5e, 0xae, 0xb8, 0x99, 0xdd, 0xbc, 0x61, 0x66,
	0x6d, 0x54, 0x21, 0x79, 0xaa, 0xfb, 0x79, 0xa1, 0x8c, 0x22, 0x2f, 0x2e, 0xd6, 0xd9, 0x65, 0xba,
	0xd6, 0xfd, 0x53, 0xb5, 0x5a, 0xa9, 0xac, 0x7f, 0xaa, 0xb2, 0x85, 0x5c, 0x76, 0x7f, 0xf7, 0x00,
	0x2e, 0x4f, 0xc6, 0xd5, 0x60, 0xd2, 0x01, 0x5f, 0xce, 0xa9, 0x77, 0xe4, 0xf5, 0x1a, 0x89, 0x2f,
	0xe7, 0xe4, 0x25, 0xd4, 0x17, 0x2a, 0x9d, 0x8b, 0x82, 0xfa, 0xc8, 0x55, 0xc8, 0xf2, 0x85, 0xc8,
	0x05, 0x37, 0xb4, 0x76, 0xe4, 0xf5, 0xa2, 0xa4, 0x42, 0xe4, 0x1b, 0x08, 0xb4, 0x11, 0xb9, 0xa6,
	0x07, 0x47, 0xb5, 0x5e, 0x73, 0xf0, 0x65, 0xff, 0xa3, 0x55, 0xfb, 0xbb, 0x8a, 0x23, 0x3b, 0x3a,
	0x71, 0x93, 0xba, 0x7f, 0xfb, 0x10, 0xef, 0xa4, 0x33, 0xc9, 0x53, 0xb5, 0x24, 0x9f, 0x41, 0x34,
	0x5f, 0x17, 0xdc, 0x48, 0x95, 0xa1, 0x31, 0x3f, 0xd9, 0x62, 0x42, 0x21, 0x34, 0x62, 0x63, 0xd6,
	0x85, 0xa8, 0xfc, 0x3d, 0x40, 0xab, 0xe4, 0x72, 0x86, 0x0a, 0x71, 0x4a, 0x05, 0xc9, 0x2b, 0x08,
	0xf5, 0x8c, 0xa7, 0x82, 0x6d, 0x68, 0x8c, 0xcb, 0xd5, 0x11, 0x4e, 0x76, 0x42, 0x49, 0x0f, 0xf7,
	0x84, 0x29, 0x69, 0x81, 0xb7, 0xc1, 0x7d, 0x06, 0x89, 0xb7, 0xb1, 0xa8, 0xa4, 0x07, 0x0e, 0x95,
	0x84, 0xc0, 0x81, 0x2d, 0x49, 0x43, 0x2c, 0x82, 0xdf, 0xe4, 0x73, 0x00, 0xfb, 0xcb, 0xee, 0xe5,
	0xdc, 0xdc, 0x50, 0xc0, 0xa1, 0x0d, 0xcb, 0xfc, 0x62, 0x09, 0xf2, 0x1a, 0x9a, 0x7a, 0xc5, 0xd3,
	0x94, 0xf1, 0xa2, 0x50, 0xf7, 0xb4, 0x89, 0x01, 0x02, 0x52, 0x43, 0xcb, 0xd8, 0x70, 0xf9, 0x1d,
	0x37, 0xbc, 0xa0, 0x2d, 0x17, 0xba, 0x43, 0xe4, 0x0b, 0x68, 0xb9, 0x2f, 0x86, 0xc6, 0x68, 0x1b,
	0x5d, 0x36, 0x1d, 0x37, 0xb2, 0x14, 0xf9, 0x14, 0xa2, 0x6a, 0xc8, 0x86, 0x76, 0xb0, 0x70, 0xe8,
	0xf0, 0x64, 0x4f, 0x2a, 0xe9, 0xf3, 0x7d, 0x69, 0xda, 0xfd, 0xf3, 0x5f, 0xb9, 0xa3, 0x09, 0x4d,
	0x3e, 0x81, 0xc0, 0x95, 0x71, 0xa1, 0x3b, 0x60, 0xd9, 0xb9, 0x48, 0x79, 0x89, 0x79, 0xfb, 0x89,
	0x03, 0x96, 0xe5, 0xd9, 0x32, 0x15, 0x55, 0x4a, 0x0e, 0xd8, 0x8a, 0x6a, 0xb1, 0xd0, 0xc2, 0xb0,
	0x0d, 0x06, 0xe6, 0x27, 0xa1, 0xc3, 0x93, 0x3d, 0xa9, 0xa4, 0xc1, 0xbe, 0x34, 0x25, 0x5d, 0x68,
	0x4b, 0xcd, 0x72, 0x25, 0x33, 0xc3, 0x66, 0x22, 0x4d, 0x69, 0x1d, 0x03, 0x6a, 0x4a, 0x7d, 0x69,
	0xb9, 0x53, 0x91, 0xa6, 0xe4, 0x05, 0xd4, 0xad, 0xc4, 0x36, 0x98, 0x7b, 0x90, 0x04, 0x16, 0x4d,
	0xb6, 0x74, 0x49, 0xa3, 0x1d, 0x3d, 0xb5, 0xf4, 0x5a, 0x32, 0x75, 0xfd, 0x81, 0x36, 0x30, 0xcf,
	0x60, 0x2d, 0xdf, 0x5f, 0x7f, 0x20, 0x27, 0x10, 0xb9, 0x2a, 0x6b, 0x89, 0x87, 0xd4, 0x19, 0xbc,
	0x7e, 0xa4, 0x5d, 0xcf, 0x71, 0xdc, 0xd5, 0xbb, 0xb7, 0xf5, 0x73, 0xf6, 0x93, 0xca, 0x44, 0x12,
	0x3a, 0x42, 0x76, 0x7f, 0x83, 0xc3, 0x5d, 0x70, 0xdf, 0x4b, 0x23, 0x2e, 0xd2, 0x12, 0x1b, 0xc9,
	0xf0, 0xc2, 0x6e, 0xdb, 0x43, 0x1f, 0x75, 0x84, 0x93, 0x9d, 0xe0, 0xe2, 0x7b, 0x10, 0xa6, 0x36,
	0x0e, 0xc3, 0x8b, 0x25, 0x26, 0xe5, 0x22, 0x0c, 0x1d, 0x9e, 0xec, 0x49, 0x0f, 0x5d, 0x57, 0x49,
	0xd3, 0xee, 0x1f, 0x1e, 0x3c, 0xdf, 0x55, 0xb7, 0xc1, 0xe8, 0xbd, 0x64, 0xbc, 0x8f, 0x27, 0xe3,
	0xef, 0x27, 0x73, 0x09, 0x0d, 0x9e, 0xc9, 0x15, 0x33, 0x65, 0xee, 0xce, 0xae, 0x33, 0xe8, 0x3d,
	0x96, 0xc1, 0xb6, 0x3d, 0x32, 0xb9, 0x1a, 0x97, 0xb9, 0x78, 0xdb, 0x18, 0x0f, 0xd9, 0xc8, 0x70,
	0x23, 0x67, 0x49, 0xc4, 0x2b, 0xd2, 0xf6, 0x6e, 0xaa, 0x66, 0xb7, 0x62, 0x8e, 0x66, 0xa3, 0xa4,
	0x42, 0xdd, 0xbf, 0x6a, 0xfb, 0x5e, 0xf1, 0xd6, 0xdb, 0xae, 0x91, 0xd9, 0x5c, 0x6c, 0xf0, 0xb4,
	0xda, 0x89, 0x03, 0xf6, 0x46, 0xad, 0xd4, 0x9d, 0x6b, 0xbb, 0x76, 0x82, 0xdf, 0x64, 0x02, 0xcd,
	0x85, 0xcc, 0xa4, 0xbe, 0x71, 0x4e, 0x7d, 0x74, 0xda, 0x7f, 0xca, 0xa9, 0xad, 0x72, 0x81, 0xd3,
	0xd0, 0x6f, 0x38, 0x1e, 0xb1, 0x1f, 0xd5, 0x9d, 0x48, 0x60, 0xb1, 0x25, 0xc9, 0xb7, 0x50, 0x9f,
	0xe3, 0x3b, 0x83, 0xdb, 0x6f, 0x0e, 0xbe, 0x7a, 0xf2, 0xc5, 0x72, 0xcf, 0x52, 0x52, 0x4d, 0x23,
	0x47, 0xd0, 0x32, 0x3c, 0x67, 0x2a, 0x63, 0xd7, 0x2a, 0x5b, 0xeb, 0x6a, 0xdb, 0x60, 0x78, 0xfe,
	0x3e, 0x3b, 0xb1, 0x8c, 0x2d, 0x81, 0x37, 0x5d, 0xd3, 0x00, 0x1f, 0xc5, 0xa7, 0x4b, 0xb8, 0x1b,
	0x98, 0x54, 0xd3, 0xc8, 0x19, 0x44, 0xb7, 0xd2, 0x88, 0x45, 0x5a, 0x6a, 0x5a, 0xc7, 0x25, 0x7a,
	0x4f, 0x2e, 0x51, 0xf5, 0x62, 0xb2, 0x9d, 0x69, 0x9f, 0x66, 0x7b, 0xe8, 0x9a, 0x86, 0xff, 0xf3,
	0x69, 0xc6, 0x86, 0x72, 0x9d, 0xa2, 0x8f, 0x39, 0x1c, 0xfe, 0xa7, 0x03, 0x48, 0x1b, 0x76, 0x3d,
	0x10, 0x3f, 0x23, 0x4d, 0x08, 0xc7, 0x43, 0xf6, 0x83, 0x58, 0x98, 0xd8, 0x23, 0x2d, 0x88, 0xc6,
	0x43, 0x96, 0xc8, 0xe5, 0x8d, 0x89, 0x7d, 0xd2, 0x80, 0x60, 0x3c, 0x64, 0x57, 0x79, 0x5c, 0xab,
	0x46, 0x9d, 0xa9, 0xfb, 0x2c, 0x3e, 0x20, 0x00, 0x75, 0x3b, 0x4a, 0x99, 0x38, 0x38, 0xfe, 0x19,
	0x5e, 0x3d, 0x72, 0x74, 0x38, 0xc7, 0x1d, 0x5e, 0xfc, 0x0c, 0x57, 0x1e, 0xb1, 0xd3, 0x54, 0xce,
	0x6e, 0x63, 0xaf, 0x92, 0xde, 0x19, 0xb1, 0x8a, 0x7d, 0xd2, 0x01, 0xa8, 0xc0, 0x95, 0x16, 0x71,
	0xed, 0xf8, 0x0a, 0xa2, 0x87, 0xbb, 0x6b, 0x4b, 0xb9, 0xdb, 0x1b, 0x3f, 0x73, 0xdf, 0xb6, 0x86,
	0x5b, 0xe0, 0x1c, 0xa7, 0x7c, 0x1d, 0xfb, 0x3b, 0x30, 0x70, 0x4e, 0x1d, 0x78, 0xe3, 0x9c, 0x9e,
	0xb3, 0xef, 0x14, 0x4f, 0xe3, 0xe0, 0xa4, 0xf5, 0x2b, 0xe0, 0xbf, 0x2c, 0xfe, 0xb3, 0xfe, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x58, 0x7d, 0x0d, 0x20, 0x72, 0x07, 0x00, 0x00,
}
