// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_editor.proto

package matchproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PBM3LevelAuthor struct {
	Account              *string  `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Token                *string  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBM3LevelAuthor) Reset()         { *m = PBM3LevelAuthor{} }
func (m *PBM3LevelAuthor) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelAuthor) ProtoMessage()    {}
func (*PBM3LevelAuthor) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{0}
}

func (m *PBM3LevelAuthor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelAuthor.Unmarshal(m, b)
}
func (m *PBM3LevelAuthor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelAuthor.Marshal(b, m, deterministic)
}
func (m *PBM3LevelAuthor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelAuthor.Merge(m, src)
}
func (m *PBM3LevelAuthor) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelAuthor.Size(m)
}
func (m *PBM3LevelAuthor) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelAuthor.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelAuthor proto.InternalMessageInfo

func (m *PBM3LevelAuthor) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *PBM3LevelAuthor) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type PBM3LevelListRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelListRequest) Reset()         { *m = PBM3LevelListRequest{} }
func (m *PBM3LevelListRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelListRequest) ProtoMessage()    {}
func (*PBM3LevelListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{1}
}

func (m *PBM3LevelListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelListRequest.Unmarshal(m, b)
}
func (m *PBM3LevelListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelListRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelListRequest.Merge(m, src)
}
func (m *PBM3LevelListRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelListRequest.Size(m)
}
func (m *PBM3LevelListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelListRequest proto.InternalMessageInfo

func (m *PBM3LevelListRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

// 关卡列表回复
type PBM3LevelListResponse struct {
	FolderList           *PBM3FolderList `protobuf:"bytes,1,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	DefaultDir           *string         `protobuf:"bytes,2,opt,name=default_dir,json=defaultDir" json:"default_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelListResponse) Reset()         { *m = PBM3LevelListResponse{} }
func (m *PBM3LevelListResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelListResponse) ProtoMessage()    {}
func (*PBM3LevelListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{2}
}

func (m *PBM3LevelListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelListResponse.Unmarshal(m, b)
}
func (m *PBM3LevelListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelListResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelListResponse.Merge(m, src)
}
func (m *PBM3LevelListResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelListResponse.Size(m)
}
func (m *PBM3LevelListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelListResponse proto.InternalMessageInfo

func (m *PBM3LevelListResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

func (m *PBM3LevelListResponse) GetDefaultDir() string {
	if m != nil && m.DefaultDir != nil {
		return *m.DefaultDir
	}
	return ""
}

//------------------------------------------------------------
// 关卡ID创建请求
type PBM3LevelIdCreateRequest struct {
	Author               *PBM3LevelAuthor    `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string             `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	Desc                 *PBLevelDescription `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Setting              *PBLevelSetting     `protobuf:"bytes,4,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelIdCreateRequest) Reset()         { *m = PBM3LevelIdCreateRequest{} }
func (m *PBM3LevelIdCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelIdCreateRequest) ProtoMessage()    {}
func (*PBM3LevelIdCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{3}
}

func (m *PBM3LevelIdCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelIdCreateRequest.Unmarshal(m, b)
}
func (m *PBM3LevelIdCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelIdCreateRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelIdCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelIdCreateRequest.Merge(m, src)
}
func (m *PBM3LevelIdCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelIdCreateRequest.Size(m)
}
func (m *PBM3LevelIdCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelIdCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelIdCreateRequest proto.InternalMessageInfo

func (m *PBM3LevelIdCreateRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelIdCreateRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelIdCreateRequest) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *PBM3LevelIdCreateRequest) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

// 关卡ID创建回复
type PBM3LevelIdCreateResponse struct {
	CurFolder            *PBM3Folder `protobuf:"bytes,1,opt,name=cur_folder,json=curFolder" json:"cur_folder,omitempty"`
	Dir                  *string     `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string     `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PBM3LevelIdCreateResponse) Reset()         { *m = PBM3LevelIdCreateResponse{} }
func (m *PBM3LevelIdCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelIdCreateResponse) ProtoMessage()    {}
func (*PBM3LevelIdCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{4}
}

func (m *PBM3LevelIdCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelIdCreateResponse.Unmarshal(m, b)
}
func (m *PBM3LevelIdCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelIdCreateResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelIdCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelIdCreateResponse.Merge(m, src)
}
func (m *PBM3LevelIdCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelIdCreateResponse.Size(m)
}
func (m *PBM3LevelIdCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelIdCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelIdCreateResponse proto.InternalMessageInfo

func (m *PBM3LevelIdCreateResponse) GetCurFolder() *PBM3Folder {
	if m != nil {
		return m.CurFolder
	}
	return nil
}

func (m *PBM3LevelIdCreateResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelIdCreateResponse) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

// 关卡权限验证请求
type PBM3LevelIdVerifyRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	VerifyType           *EVerifyType     `protobuf:"varint,2,opt,name=verify_type,json=verifyType,enum=FunPlus.Common.Config.EVerifyType,def=0" json:"verify_type,omitempty"`
	DstDir               *string          `protobuf:"bytes,3,opt,name=dst_dir,json=dstDir" json:"dst_dir,omitempty"`
	SrcDir               *string          `protobuf:"bytes,4,opt,name=src_dir,json=srcDir" json:"src_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelIdVerifyRequest) Reset()         { *m = PBM3LevelIdVerifyRequest{} }
func (m *PBM3LevelIdVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelIdVerifyRequest) ProtoMessage()    {}
func (*PBM3LevelIdVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{5}
}

func (m *PBM3LevelIdVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelIdVerifyRequest.Unmarshal(m, b)
}
func (m *PBM3LevelIdVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelIdVerifyRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelIdVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelIdVerifyRequest.Merge(m, src)
}
func (m *PBM3LevelIdVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelIdVerifyRequest.Size(m)
}
func (m *PBM3LevelIdVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelIdVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelIdVerifyRequest proto.InternalMessageInfo

const Default_PBM3LevelIdVerifyRequest_VerifyType EVerifyType = EVerifyType_E_Verify_Create

func (m *PBM3LevelIdVerifyRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelIdVerifyRequest) GetVerifyType() EVerifyType {
	if m != nil && m.VerifyType != nil {
		return *m.VerifyType
	}
	return Default_PBM3LevelIdVerifyRequest_VerifyType
}

func (m *PBM3LevelIdVerifyRequest) GetDstDir() string {
	if m != nil && m.DstDir != nil {
		return *m.DstDir
	}
	return ""
}

func (m *PBM3LevelIdVerifyRequest) GetSrcDir() string {
	if m != nil && m.SrcDir != nil {
		return *m.SrcDir
	}
	return ""
}

// 关卡权限验证回复
type PBM3LevelIdVerifyResponse struct {
	RetCode              *int32       `protobuf:"zigzag32,1,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	VerifyType           *EVerifyType `protobuf:"varint,2,opt,name=verify_type,json=verifyType,enum=FunPlus.Common.Config.EVerifyType,def=0" json:"verify_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PBM3LevelIdVerifyResponse) Reset()         { *m = PBM3LevelIdVerifyResponse{} }
func (m *PBM3LevelIdVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelIdVerifyResponse) ProtoMessage()    {}
func (*PBM3LevelIdVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{6}
}

func (m *PBM3LevelIdVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelIdVerifyResponse.Unmarshal(m, b)
}
func (m *PBM3LevelIdVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelIdVerifyResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelIdVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelIdVerifyResponse.Merge(m, src)
}
func (m *PBM3LevelIdVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelIdVerifyResponse.Size(m)
}
func (m *PBM3LevelIdVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelIdVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelIdVerifyResponse proto.InternalMessageInfo

const Default_PBM3LevelIdVerifyResponse_VerifyType EVerifyType = EVerifyType_E_Verify_Create

func (m *PBM3LevelIdVerifyResponse) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *PBM3LevelIdVerifyResponse) GetVerifyType() EVerifyType {
	if m != nil && m.VerifyType != nil {
		return *m.VerifyType
	}
	return Default_PBM3LevelIdVerifyResponse_VerifyType
}

// 取关卡数据请求
type PBM3LevelSettingRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string          `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelSettingRequest) Reset()         { *m = PBM3LevelSettingRequest{} }
func (m *PBM3LevelSettingRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelSettingRequest) ProtoMessage()    {}
func (*PBM3LevelSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{7}
}

func (m *PBM3LevelSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelSettingRequest.Unmarshal(m, b)
}
func (m *PBM3LevelSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelSettingRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelSettingRequest.Merge(m, src)
}
func (m *PBM3LevelSettingRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelSettingRequest.Size(m)
}
func (m *PBM3LevelSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelSettingRequest proto.InternalMessageInfo

func (m *PBM3LevelSettingRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelSettingRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelSettingRequest) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

//取关卡数据回复
type PBM3LevelSettingResponse struct {
	Dir                  *string             `protobuf:"bytes,1,opt,name=dir" json:"dir,omitempty"`
	Desc                 *PBLevelDescription `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Setting              *PBLevelSetting     `protobuf:"bytes,3,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelSettingResponse) Reset()         { *m = PBM3LevelSettingResponse{} }
func (m *PBM3LevelSettingResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelSettingResponse) ProtoMessage()    {}
func (*PBM3LevelSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{8}
}

func (m *PBM3LevelSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelSettingResponse.Unmarshal(m, b)
}
func (m *PBM3LevelSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelSettingResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelSettingResponse.Merge(m, src)
}
func (m *PBM3LevelSettingResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelSettingResponse.Size(m)
}
func (m *PBM3LevelSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelSettingResponse proto.InternalMessageInfo

func (m *PBM3LevelSettingResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelSettingResponse) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *PBM3LevelSettingResponse) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

//关卡锁定请求
type PBM3LevelLockRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string          `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelLockRequest) Reset()         { *m = PBM3LevelLockRequest{} }
func (m *PBM3LevelLockRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelLockRequest) ProtoMessage()    {}
func (*PBM3LevelLockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{9}
}

func (m *PBM3LevelLockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelLockRequest.Unmarshal(m, b)
}
func (m *PBM3LevelLockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelLockRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelLockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelLockRequest.Merge(m, src)
}
func (m *PBM3LevelLockRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelLockRequest.Size(m)
}
func (m *PBM3LevelLockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelLockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelLockRequest proto.InternalMessageInfo

func (m *PBM3LevelLockRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelLockRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelLockRequest) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

type PBM3LevelLockResponse struct {
	Desc                 *PBLevelDescription `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelLockResponse) Reset()         { *m = PBM3LevelLockResponse{} }
func (m *PBM3LevelLockResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelLockResponse) ProtoMessage()    {}
func (*PBM3LevelLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{10}
}

func (m *PBM3LevelLockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelLockResponse.Unmarshal(m, b)
}
func (m *PBM3LevelLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelLockResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelLockResponse.Merge(m, src)
}
func (m *PBM3LevelLockResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelLockResponse.Size(m)
}
func (m *PBM3LevelLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelLockResponse proto.InternalMessageInfo

func (m *PBM3LevelLockResponse) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

type PBM3LevelUnlockRequest struct {
	Author               *PBM3LevelAuthor    `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string             `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	Desc                 *PBLevelDescription `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Setting              *PBLevelSetting     `protobuf:"bytes,4,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelUnlockRequest) Reset()         { *m = PBM3LevelUnlockRequest{} }
func (m *PBM3LevelUnlockRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelUnlockRequest) ProtoMessage()    {}
func (*PBM3LevelUnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{11}
}

func (m *PBM3LevelUnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelUnlockRequest.Unmarshal(m, b)
}
func (m *PBM3LevelUnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelUnlockRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelUnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelUnlockRequest.Merge(m, src)
}
func (m *PBM3LevelUnlockRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelUnlockRequest.Size(m)
}
func (m *PBM3LevelUnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelUnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelUnlockRequest proto.InternalMessageInfo

func (m *PBM3LevelUnlockRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelUnlockRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelUnlockRequest) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *PBM3LevelUnlockRequest) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

type PBM3LevelUnlockResponse struct {
	Desc                 *PBLevelDescription `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelUnlockResponse) Reset()         { *m = PBM3LevelUnlockResponse{} }
func (m *PBM3LevelUnlockResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelUnlockResponse) ProtoMessage()    {}
func (*PBM3LevelUnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{12}
}

func (m *PBM3LevelUnlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelUnlockResponse.Unmarshal(m, b)
}
func (m *PBM3LevelUnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelUnlockResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelUnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelUnlockResponse.Merge(m, src)
}
func (m *PBM3LevelUnlockResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelUnlockResponse.Size(m)
}
func (m *PBM3LevelUnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelUnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelUnlockResponse proto.InternalMessageInfo

func (m *PBM3LevelUnlockResponse) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

type PBM3LevelDeleteRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string          `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelDeleteRequest) Reset()         { *m = PBM3LevelDeleteRequest{} }
func (m *PBM3LevelDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelDeleteRequest) ProtoMessage()    {}
func (*PBM3LevelDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{13}
}

func (m *PBM3LevelDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelDeleteRequest.Unmarshal(m, b)
}
func (m *PBM3LevelDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelDeleteRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelDeleteRequest.Merge(m, src)
}
func (m *PBM3LevelDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelDeleteRequest.Size(m)
}
func (m *PBM3LevelDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelDeleteRequest proto.InternalMessageInfo

func (m *PBM3LevelDeleteRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelDeleteRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelDeleteRequest) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

type PBM3LevelDeleteResponse struct {
	FolderList           *PBM3FolderList `protobuf:"bytes,1,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelDeleteResponse) Reset()         { *m = PBM3LevelDeleteResponse{} }
func (m *PBM3LevelDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelDeleteResponse) ProtoMessage()    {}
func (*PBM3LevelDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{14}
}

func (m *PBM3LevelDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelDeleteResponse.Unmarshal(m, b)
}
func (m *PBM3LevelDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelDeleteResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelDeleteResponse.Merge(m, src)
}
func (m *PBM3LevelDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelDeleteResponse.Size(m)
}
func (m *PBM3LevelDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelDeleteResponse proto.InternalMessageInfo

func (m *PBM3LevelDeleteResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

type PBM3LevelMoveRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string          `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	ToDir                *string          `protobuf:"bytes,4,opt,name=to_dir,json=toDir" json:"to_dir,omitempty"`
	Order                *int32           `protobuf:"varint,5,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelMoveRequest) Reset()         { *m = PBM3LevelMoveRequest{} }
func (m *PBM3LevelMoveRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelMoveRequest) ProtoMessage()    {}
func (*PBM3LevelMoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{15}
}

func (m *PBM3LevelMoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelMoveRequest.Unmarshal(m, b)
}
func (m *PBM3LevelMoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelMoveRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelMoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelMoveRequest.Merge(m, src)
}
func (m *PBM3LevelMoveRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelMoveRequest.Size(m)
}
func (m *PBM3LevelMoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelMoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelMoveRequest proto.InternalMessageInfo

func (m *PBM3LevelMoveRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelMoveRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelMoveRequest) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

func (m *PBM3LevelMoveRequest) GetToDir() string {
	if m != nil && m.ToDir != nil {
		return *m.ToDir
	}
	return ""
}

func (m *PBM3LevelMoveRequest) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

type PBM3LevelMoveResponse struct {
	FolderList           *PBM3FolderList `protobuf:"bytes,1,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	Dir                  *string         `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string         `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelMoveResponse) Reset()         { *m = PBM3LevelMoveResponse{} }
func (m *PBM3LevelMoveResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelMoveResponse) ProtoMessage()    {}
func (*PBM3LevelMoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{16}
}

func (m *PBM3LevelMoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelMoveResponse.Unmarshal(m, b)
}
func (m *PBM3LevelMoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelMoveResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelMoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelMoveResponse.Merge(m, src)
}
func (m *PBM3LevelMoveResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelMoveResponse.Size(m)
}
func (m *PBM3LevelMoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelMoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelMoveResponse proto.InternalMessageInfo

func (m *PBM3LevelMoveResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

func (m *PBM3LevelMoveResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelMoveResponse) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

type PBM3LevelCopyRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string          `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	ToDir                *string          `protobuf:"bytes,4,opt,name=to_dir,json=toDir" json:"to_dir,omitempty"`
	Order                *int32           `protobuf:"varint,5,opt,name=order" json:"order,omitempty"`
	NewLevelId           *string          `protobuf:"bytes,6,opt,name=new_level_id,json=newLevelId" json:"new_level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelCopyRequest) Reset()         { *m = PBM3LevelCopyRequest{} }
func (m *PBM3LevelCopyRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelCopyRequest) ProtoMessage()    {}
func (*PBM3LevelCopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{17}
}

func (m *PBM3LevelCopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelCopyRequest.Unmarshal(m, b)
}
func (m *PBM3LevelCopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelCopyRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelCopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelCopyRequest.Merge(m, src)
}
func (m *PBM3LevelCopyRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelCopyRequest.Size(m)
}
func (m *PBM3LevelCopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelCopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelCopyRequest proto.InternalMessageInfo

func (m *PBM3LevelCopyRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelCopyRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelCopyRequest) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

func (m *PBM3LevelCopyRequest) GetToDir() string {
	if m != nil && m.ToDir != nil {
		return *m.ToDir
	}
	return ""
}

func (m *PBM3LevelCopyRequest) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

func (m *PBM3LevelCopyRequest) GetNewLevelId() string {
	if m != nil && m.NewLevelId != nil {
		return *m.NewLevelId
	}
	return ""
}

type PBM3LevelCopyResponse struct {
	FolderList           *PBM3FolderList `protobuf:"bytes,1,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	Dir                  *string         `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string         `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelCopyResponse) Reset()         { *m = PBM3LevelCopyResponse{} }
func (m *PBM3LevelCopyResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelCopyResponse) ProtoMessage()    {}
func (*PBM3LevelCopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{18}
}

func (m *PBM3LevelCopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelCopyResponse.Unmarshal(m, b)
}
func (m *PBM3LevelCopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelCopyResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelCopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelCopyResponse.Merge(m, src)
}
func (m *PBM3LevelCopyResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelCopyResponse.Size(m)
}
func (m *PBM3LevelCopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelCopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelCopyResponse proto.InternalMessageInfo

func (m *PBM3LevelCopyResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

func (m *PBM3LevelCopyResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelCopyResponse) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

//------------------------------------------------------------
// 关卡导入请求
type PBM3LevelImportRequest struct {
	Author               *PBM3LevelAuthor    `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string             `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	Desc                 *PBLevelDescription `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Setting              *PBLevelSetting     `protobuf:"bytes,4,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelImportRequest) Reset()         { *m = PBM3LevelImportRequest{} }
func (m *PBM3LevelImportRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelImportRequest) ProtoMessage()    {}
func (*PBM3LevelImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{19}
}

func (m *PBM3LevelImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelImportRequest.Unmarshal(m, b)
}
func (m *PBM3LevelImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelImportRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelImportRequest.Merge(m, src)
}
func (m *PBM3LevelImportRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelImportRequest.Size(m)
}
func (m *PBM3LevelImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelImportRequest proto.InternalMessageInfo

func (m *PBM3LevelImportRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelImportRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelImportRequest) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *PBM3LevelImportRequest) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

// 关卡导入回复
type PBM3LevelImportResponse struct {
	CurFolder            *PBM3Folder `protobuf:"bytes,1,opt,name=cur_folder,json=curFolder" json:"cur_folder,omitempty"`
	Dir                  *string     `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string     `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PBM3LevelImportResponse) Reset()         { *m = PBM3LevelImportResponse{} }
func (m *PBM3LevelImportResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelImportResponse) ProtoMessage()    {}
func (*PBM3LevelImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{20}
}

func (m *PBM3LevelImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelImportResponse.Unmarshal(m, b)
}
func (m *PBM3LevelImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelImportResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelImportResponse.Merge(m, src)
}
func (m *PBM3LevelImportResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelImportResponse.Size(m)
}
func (m *PBM3LevelImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelImportResponse proto.InternalMessageInfo

func (m *PBM3LevelImportResponse) GetCurFolder() *PBM3Folder {
	if m != nil {
		return m.CurFolder
	}
	return nil
}

func (m *PBM3LevelImportResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelImportResponse) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

type PBM3LevelCopyLockRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              *string          `protobuf:"bytes,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	ToDir                *string          `protobuf:"bytes,4,opt,name=to_dir,json=toDir" json:"to_dir,omitempty"`
	Order                *int32           `protobuf:"varint,5,opt,name=order" json:"order,omitempty"`
	NewLevelId           *string          `protobuf:"bytes,6,opt,name=new_level_id,json=newLevelId" json:"new_level_id,omitempty"`
	Setting              *PBLevelSetting  `protobuf:"bytes,7,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelCopyLockRequest) Reset()         { *m = PBM3LevelCopyLockRequest{} }
func (m *PBM3LevelCopyLockRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelCopyLockRequest) ProtoMessage()    {}
func (*PBM3LevelCopyLockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{21}
}

func (m *PBM3LevelCopyLockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelCopyLockRequest.Unmarshal(m, b)
}
func (m *PBM3LevelCopyLockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelCopyLockRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelCopyLockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelCopyLockRequest.Merge(m, src)
}
func (m *PBM3LevelCopyLockRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelCopyLockRequest.Size(m)
}
func (m *PBM3LevelCopyLockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelCopyLockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelCopyLockRequest proto.InternalMessageInfo

func (m *PBM3LevelCopyLockRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelCopyLockRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelCopyLockRequest) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

func (m *PBM3LevelCopyLockRequest) GetToDir() string {
	if m != nil && m.ToDir != nil {
		return *m.ToDir
	}
	return ""
}

func (m *PBM3LevelCopyLockRequest) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

func (m *PBM3LevelCopyLockRequest) GetNewLevelId() string {
	if m != nil && m.NewLevelId != nil {
		return *m.NewLevelId
	}
	return ""
}

func (m *PBM3LevelCopyLockRequest) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

type PBM3LevelBatchDeleteRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelIdList          []string         `protobuf:"bytes,3,rep,name=level_id_list,json=levelIdList" json:"level_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelBatchDeleteRequest) Reset()         { *m = PBM3LevelBatchDeleteRequest{} }
func (m *PBM3LevelBatchDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchDeleteRequest) ProtoMessage()    {}
func (*PBM3LevelBatchDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{22}
}

func (m *PBM3LevelBatchDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchDeleteRequest.Unmarshal(m, b)
}
func (m *PBM3LevelBatchDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchDeleteRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchDeleteRequest.Merge(m, src)
}
func (m *PBM3LevelBatchDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchDeleteRequest.Size(m)
}
func (m *PBM3LevelBatchDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchDeleteRequest proto.InternalMessageInfo

func (m *PBM3LevelBatchDeleteRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelBatchDeleteRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelBatchDeleteRequest) GetLevelIdList() []string {
	if m != nil {
		return m.LevelIdList
	}
	return nil
}

type PBM3LevelBatchDeleteResponse struct {
	RetCode              *int32          `protobuf:"zigzag32,1,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	ErrLevelId           *string         `protobuf:"bytes,2,opt,name=err_level_id,json=errLevelId" json:"err_level_id,omitempty"`
	FolderList           *PBM3FolderList `protobuf:"bytes,3,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelBatchDeleteResponse) Reset()         { *m = PBM3LevelBatchDeleteResponse{} }
func (m *PBM3LevelBatchDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchDeleteResponse) ProtoMessage()    {}
func (*PBM3LevelBatchDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{23}
}

func (m *PBM3LevelBatchDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchDeleteResponse.Unmarshal(m, b)
}
func (m *PBM3LevelBatchDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchDeleteResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchDeleteResponse.Merge(m, src)
}
func (m *PBM3LevelBatchDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchDeleteResponse.Size(m)
}
func (m *PBM3LevelBatchDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchDeleteResponse proto.InternalMessageInfo

func (m *PBM3LevelBatchDeleteResponse) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *PBM3LevelBatchDeleteResponse) GetErrLevelId() string {
	if m != nil && m.ErrLevelId != nil {
		return *m.ErrLevelId
	}
	return ""
}

func (m *PBM3LevelBatchDeleteResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

type PBM3LevelBatchUnlockItem struct {
	Desc                 *PBLevelDescription `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
	Setting              *PBLevelSetting     `protobuf:"bytes,2,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelBatchUnlockItem) Reset()         { *m = PBM3LevelBatchUnlockItem{} }
func (m *PBM3LevelBatchUnlockItem) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchUnlockItem) ProtoMessage()    {}
func (*PBM3LevelBatchUnlockItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{24}
}

func (m *PBM3LevelBatchUnlockItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchUnlockItem.Unmarshal(m, b)
}
func (m *PBM3LevelBatchUnlockItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchUnlockItem.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchUnlockItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchUnlockItem.Merge(m, src)
}
func (m *PBM3LevelBatchUnlockItem) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchUnlockItem.Size(m)
}
func (m *PBM3LevelBatchUnlockItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchUnlockItem.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchUnlockItem proto.InternalMessageInfo

func (m *PBM3LevelBatchUnlockItem) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *PBM3LevelBatchUnlockItem) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

type PBM3LevelBatchUnlockRequest struct {
	Author               *PBM3LevelAuthor            `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string                     `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	UnlockItemList       []*PBM3LevelBatchUnlockItem `protobuf:"bytes,3,rep,name=unlock_item_list,json=unlockItemList" json:"unlock_item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PBM3LevelBatchUnlockRequest) Reset()         { *m = PBM3LevelBatchUnlockRequest{} }
func (m *PBM3LevelBatchUnlockRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchUnlockRequest) ProtoMessage()    {}
func (*PBM3LevelBatchUnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{25}
}

func (m *PBM3LevelBatchUnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchUnlockRequest.Unmarshal(m, b)
}
func (m *PBM3LevelBatchUnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchUnlockRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchUnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchUnlockRequest.Merge(m, src)
}
func (m *PBM3LevelBatchUnlockRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchUnlockRequest.Size(m)
}
func (m *PBM3LevelBatchUnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchUnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchUnlockRequest proto.InternalMessageInfo

func (m *PBM3LevelBatchUnlockRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelBatchUnlockRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelBatchUnlockRequest) GetUnlockItemList() []*PBM3LevelBatchUnlockItem {
	if m != nil {
		return m.UnlockItemList
	}
	return nil
}

type PBM3LevelBatchUnlockResponse struct {
	RetCode              *int32                `protobuf:"zigzag32,1,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	ErrLevelId           *string               `protobuf:"bytes,2,opt,name=err_level_id,json=errLevelId" json:"err_level_id,omitempty"`
	DescList             []*PBLevelDescription `protobuf:"bytes,3,rep,name=desc_list,json=descList" json:"desc_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PBM3LevelBatchUnlockResponse) Reset()         { *m = PBM3LevelBatchUnlockResponse{} }
func (m *PBM3LevelBatchUnlockResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchUnlockResponse) ProtoMessage()    {}
func (*PBM3LevelBatchUnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{26}
}

func (m *PBM3LevelBatchUnlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchUnlockResponse.Unmarshal(m, b)
}
func (m *PBM3LevelBatchUnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchUnlockResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchUnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchUnlockResponse.Merge(m, src)
}
func (m *PBM3LevelBatchUnlockResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchUnlockResponse.Size(m)
}
func (m *PBM3LevelBatchUnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchUnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchUnlockResponse proto.InternalMessageInfo

func (m *PBM3LevelBatchUnlockResponse) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *PBM3LevelBatchUnlockResponse) GetErrLevelId() string {
	if m != nil && m.ErrLevelId != nil {
		return *m.ErrLevelId
	}
	return ""
}

func (m *PBM3LevelBatchUnlockResponse) GetDescList() []*PBLevelDescription {
	if m != nil {
		return m.DescList
	}
	return nil
}

type PBM3LevelBatchMoveRequest struct {
	Author               *PBM3LevelAuthor `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string          `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelIdList          []string         `protobuf:"bytes,3,rep,name=level_id_list,json=levelIdList" json:"level_id_list,omitempty"`
	ToDir                *string          `protobuf:"bytes,4,opt,name=to_dir,json=toDir" json:"to_dir,omitempty"`
	Order                *int32           `protobuf:"varint,5,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PBM3LevelBatchMoveRequest) Reset()         { *m = PBM3LevelBatchMoveRequest{} }
func (m *PBM3LevelBatchMoveRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchMoveRequest) ProtoMessage()    {}
func (*PBM3LevelBatchMoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{27}
}

func (m *PBM3LevelBatchMoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchMoveRequest.Unmarshal(m, b)
}
func (m *PBM3LevelBatchMoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchMoveRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchMoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchMoveRequest.Merge(m, src)
}
func (m *PBM3LevelBatchMoveRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchMoveRequest.Size(m)
}
func (m *PBM3LevelBatchMoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchMoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchMoveRequest proto.InternalMessageInfo

func (m *PBM3LevelBatchMoveRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelBatchMoveRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelBatchMoveRequest) GetLevelIdList() []string {
	if m != nil {
		return m.LevelIdList
	}
	return nil
}

func (m *PBM3LevelBatchMoveRequest) GetToDir() string {
	if m != nil && m.ToDir != nil {
		return *m.ToDir
	}
	return ""
}

func (m *PBM3LevelBatchMoveRequest) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

type PBM3LevelBatchMoveResponse struct {
	FolderList           *PBM3FolderList `protobuf:"bytes,1,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	Dir                  *string         `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelIdList          []string        `protobuf:"bytes,3,rep,name=level_id_list,json=levelIdList" json:"level_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelBatchMoveResponse) Reset()         { *m = PBM3LevelBatchMoveResponse{} }
func (m *PBM3LevelBatchMoveResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchMoveResponse) ProtoMessage()    {}
func (*PBM3LevelBatchMoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{28}
}

func (m *PBM3LevelBatchMoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchMoveResponse.Unmarshal(m, b)
}
func (m *PBM3LevelBatchMoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchMoveResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchMoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchMoveResponse.Merge(m, src)
}
func (m *PBM3LevelBatchMoveResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchMoveResponse.Size(m)
}
func (m *PBM3LevelBatchMoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchMoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchMoveResponse proto.InternalMessageInfo

func (m *PBM3LevelBatchMoveResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

func (m *PBM3LevelBatchMoveResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelBatchMoveResponse) GetLevelIdList() []string {
	if m != nil {
		return m.LevelIdList
	}
	return nil
}

type PBM3LevelBatchCopyItem struct {
	LevelId              *string  `protobuf:"bytes,1,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	NewLevelId           *string  `protobuf:"bytes,2,opt,name=new_level_id,json=newLevelId" json:"new_level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBM3LevelBatchCopyItem) Reset()         { *m = PBM3LevelBatchCopyItem{} }
func (m *PBM3LevelBatchCopyItem) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchCopyItem) ProtoMessage()    {}
func (*PBM3LevelBatchCopyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{29}
}

func (m *PBM3LevelBatchCopyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchCopyItem.Unmarshal(m, b)
}
func (m *PBM3LevelBatchCopyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchCopyItem.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchCopyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchCopyItem.Merge(m, src)
}
func (m *PBM3LevelBatchCopyItem) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchCopyItem.Size(m)
}
func (m *PBM3LevelBatchCopyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchCopyItem.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchCopyItem proto.InternalMessageInfo

func (m *PBM3LevelBatchCopyItem) GetLevelId() string {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return ""
}

func (m *PBM3LevelBatchCopyItem) GetNewLevelId() string {
	if m != nil && m.NewLevelId != nil {
		return *m.NewLevelId
	}
	return ""
}

type PBM3LevelBatchCopyRequest struct {
	Author               *PBM3LevelAuthor          `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string                   `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	ToDir                *string                   `protobuf:"bytes,3,opt,name=to_dir,json=toDir" json:"to_dir,omitempty"`
	Order                *int32                    `protobuf:"varint,4,opt,name=order" json:"order,omitempty"`
	CopyItemList         []*PBM3LevelBatchCopyItem `protobuf:"bytes,5,rep,name=copy_item_list,json=copyItemList" json:"copy_item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PBM3LevelBatchCopyRequest) Reset()         { *m = PBM3LevelBatchCopyRequest{} }
func (m *PBM3LevelBatchCopyRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchCopyRequest) ProtoMessage()    {}
func (*PBM3LevelBatchCopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{30}
}

func (m *PBM3LevelBatchCopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchCopyRequest.Unmarshal(m, b)
}
func (m *PBM3LevelBatchCopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchCopyRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchCopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchCopyRequest.Merge(m, src)
}
func (m *PBM3LevelBatchCopyRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchCopyRequest.Size(m)
}
func (m *PBM3LevelBatchCopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchCopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchCopyRequest proto.InternalMessageInfo

func (m *PBM3LevelBatchCopyRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelBatchCopyRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelBatchCopyRequest) GetToDir() string {
	if m != nil && m.ToDir != nil {
		return *m.ToDir
	}
	return ""
}

func (m *PBM3LevelBatchCopyRequest) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

func (m *PBM3LevelBatchCopyRequest) GetCopyItemList() []*PBM3LevelBatchCopyItem {
	if m != nil {
		return m.CopyItemList
	}
	return nil
}

type PBM3LevelBatchCopyResponse struct {
	FolderList           *PBM3FolderList `protobuf:"bytes,1,opt,name=folder_list,json=folderList" json:"folder_list,omitempty"`
	Dir                  *string         `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	LevelId              []string        `protobuf:"bytes,3,rep,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBM3LevelBatchCopyResponse) Reset()         { *m = PBM3LevelBatchCopyResponse{} }
func (m *PBM3LevelBatchCopyResponse) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelBatchCopyResponse) ProtoMessage()    {}
func (*PBM3LevelBatchCopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{31}
}

func (m *PBM3LevelBatchCopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelBatchCopyResponse.Unmarshal(m, b)
}
func (m *PBM3LevelBatchCopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelBatchCopyResponse.Marshal(b, m, deterministic)
}
func (m *PBM3LevelBatchCopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelBatchCopyResponse.Merge(m, src)
}
func (m *PBM3LevelBatchCopyResponse) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelBatchCopyResponse.Size(m)
}
func (m *PBM3LevelBatchCopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelBatchCopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelBatchCopyResponse proto.InternalMessageInfo

func (m *PBM3LevelBatchCopyResponse) GetFolderList() *PBM3FolderList {
	if m != nil {
		return m.FolderList
	}
	return nil
}

func (m *PBM3LevelBatchCopyResponse) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelBatchCopyResponse) GetLevelId() []string {
	if m != nil {
		return m.LevelId
	}
	return nil
}

type PBM3LevelModifySyncRequest struct {
	Author               *PBM3LevelAuthor    `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Dir                  *string             `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	Desc                 *PBLevelDescription `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Setting              *PBLevelSetting     `protobuf:"bytes,4,opt,name=setting" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBM3LevelModifySyncRequest) Reset()         { *m = PBM3LevelModifySyncRequest{} }
func (m *PBM3LevelModifySyncRequest) String() string { return proto.CompactTextString(m) }
func (*PBM3LevelModifySyncRequest) ProtoMessage()    {}
func (*PBM3LevelModifySyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82483b9d25cd49c2, []int{32}
}

func (m *PBM3LevelModifySyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBM3LevelModifySyncRequest.Unmarshal(m, b)
}
func (m *PBM3LevelModifySyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBM3LevelModifySyncRequest.Marshal(b, m, deterministic)
}
func (m *PBM3LevelModifySyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBM3LevelModifySyncRequest.Merge(m, src)
}
func (m *PBM3LevelModifySyncRequest) XXX_Size() int {
	return xxx_messageInfo_PBM3LevelModifySyncRequest.Size(m)
}
func (m *PBM3LevelModifySyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBM3LevelModifySyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBM3LevelModifySyncRequest proto.InternalMessageInfo

func (m *PBM3LevelModifySyncRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBM3LevelModifySyncRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *PBM3LevelModifySyncRequest) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *PBM3LevelModifySyncRequest) GetSetting() *PBLevelSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

func init() {
	proto.RegisterType((*PBM3LevelAuthor)(nil), "FunPlus.Common.Config.PBM3LevelAuthor")
	proto.RegisterType((*PBM3LevelListRequest)(nil), "FunPlus.Common.Config.PBM3LevelListRequest")
	proto.RegisterType((*PBM3LevelListResponse)(nil), "FunPlus.Common.Config.PBM3LevelListResponse")
	proto.RegisterType((*PBM3LevelIdCreateRequest)(nil), "FunPlus.Common.Config.PBM3LevelIdCreateRequest")
	proto.RegisterType((*PBM3LevelIdCreateResponse)(nil), "FunPlus.Common.Config.PBM3LevelIdCreateResponse")
	proto.RegisterType((*PBM3LevelIdVerifyRequest)(nil), "FunPlus.Common.Config.PBM3LevelIdVerifyRequest")
	proto.RegisterType((*PBM3LevelIdVerifyResponse)(nil), "FunPlus.Common.Config.PBM3LevelIdVerifyResponse")
	proto.RegisterType((*PBM3LevelSettingRequest)(nil), "FunPlus.Common.Config.PBM3LevelSettingRequest")
	proto.RegisterType((*PBM3LevelSettingResponse)(nil), "FunPlus.Common.Config.PBM3LevelSettingResponse")
	proto.RegisterType((*PBM3LevelLockRequest)(nil), "FunPlus.Common.Config.PBM3LevelLockRequest")
	proto.RegisterType((*PBM3LevelLockResponse)(nil), "FunPlus.Common.Config.PBM3LevelLockResponse")
	proto.RegisterType((*PBM3LevelUnlockRequest)(nil), "FunPlus.Common.Config.PBM3LevelUnlockRequest")
	proto.RegisterType((*PBM3LevelUnlockResponse)(nil), "FunPlus.Common.Config.PBM3LevelUnlockResponse")
	proto.RegisterType((*PBM3LevelDeleteRequest)(nil), "FunPlus.Common.Config.PBM3LevelDeleteRequest")
	proto.RegisterType((*PBM3LevelDeleteResponse)(nil), "FunPlus.Common.Config.PBM3LevelDeleteResponse")
	proto.RegisterType((*PBM3LevelMoveRequest)(nil), "FunPlus.Common.Config.PBM3LevelMoveRequest")
	proto.RegisterType((*PBM3LevelMoveResponse)(nil), "FunPlus.Common.Config.PBM3LevelMoveResponse")
	proto.RegisterType((*PBM3LevelCopyRequest)(nil), "FunPlus.Common.Config.PBM3LevelCopyRequest")
	proto.RegisterType((*PBM3LevelCopyResponse)(nil), "FunPlus.Common.Config.PBM3LevelCopyResponse")
	proto.RegisterType((*PBM3LevelImportRequest)(nil), "FunPlus.Common.Config.PBM3LevelImportRequest")
	proto.RegisterType((*PBM3LevelImportResponse)(nil), "FunPlus.Common.Config.PBM3LevelImportResponse")
	proto.RegisterType((*PBM3LevelCopyLockRequest)(nil), "FunPlus.Common.Config.PBM3LevelCopyLockRequest")
	proto.RegisterType((*PBM3LevelBatchDeleteRequest)(nil), "FunPlus.Common.Config.PBM3LevelBatchDeleteRequest")
	proto.RegisterType((*PBM3LevelBatchDeleteResponse)(nil), "FunPlus.Common.Config.PBM3LevelBatchDeleteResponse")
	proto.RegisterType((*PBM3LevelBatchUnlockItem)(nil), "FunPlus.Common.Config.PBM3LevelBatchUnlockItem")
	proto.RegisterType((*PBM3LevelBatchUnlockRequest)(nil), "FunPlus.Common.Config.PBM3LevelBatchUnlockRequest")
	proto.RegisterType((*PBM3LevelBatchUnlockResponse)(nil), "FunPlus.Common.Config.PBM3LevelBatchUnlockResponse")
	proto.RegisterType((*PBM3LevelBatchMoveRequest)(nil), "FunPlus.Common.Config.PBM3LevelBatchMoveRequest")
	proto.RegisterType((*PBM3LevelBatchMoveResponse)(nil), "FunPlus.Common.Config.PBM3LevelBatchMoveResponse")
	proto.RegisterType((*PBM3LevelBatchCopyItem)(nil), "FunPlus.Common.Config.PBM3LevelBatchCopyItem")
	proto.RegisterType((*PBM3LevelBatchCopyRequest)(nil), "FunPlus.Common.Config.PBM3LevelBatchCopyRequest")
	proto.RegisterType((*PBM3LevelBatchCopyResponse)(nil), "FunPlus.Common.Config.PBM3LevelBatchCopyResponse")
	proto.RegisterType((*PBM3LevelModifySyncRequest)(nil), "FunPlus.Common.Config.PBM3LevelModifySyncRequest")
}

func init() { proto.RegisterFile("msg_editor.proto", fileDescriptor_82483b9d25cd49c2) }

var fileDescriptor_82483b9d25cd49c2 = []byte{
	// 1069 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0x96, 0x93, 0xa6, 0x99, 0xbc, 0x29, 0xdd, 0x62, 0x5a, 0x36, 0x2d, 0x48, 0x84, 0x91, 0x40,
	0xe5, 0x40, 0x90, 0xca, 0x6d, 0x25, 0x3e, 0xb6, 0xe9, 0x56, 0xaa, 0xd4, 0x4a, 0x2b, 0x77, 0x17,
	0x09, 0xa4, 0x95, 0x15, 0xec, 0x49, 0x6b, 0xad, 0xe3, 0x09, 0xe3, 0x71, 0x57, 0x39, 0x20, 0x19,
	0x76, 0xd9, 0xef, 0xee, 0x0a, 0x71, 0x41, 0x1c, 0x90, 0xb9, 0x72, 0xe5, 0xc0, 0x2f, 0xe0, 0x07,
	0x70, 0xe4, 0x27, 0x70, 0x44, 0x08, 0xce, 0x2b, 0xcf, 0xd8, 0xce, 0xd4, 0xcd, 0xf6, 0x33, 0x56,
	0x56, 0x7b, 0x1b, 0x8f, 0x3d, 0xef, 0x3c, 0xcf, 0xf3, 0x7e, 0x26, 0x30, 0xd7, 0xf3, 0x77, 0x4c,
	0x62, 0x3b, 0x9c, 0xb2, 0x56, 0x9f, 0x51, 0x4e, 0xf5, 0x85, 0xf5, 0xc0, 0xbb, 0xea, 0x06, 0x7e,
	0xab, 0x4d, 0x7b, 0x3d, 0xea, 0xb5, 0xda, 0xd4, 0xeb, 0x3a, 0x3b, 0x4b, 0xb3, 0xf1, 0x87, 0x5f,
	0x76, 0x7c, 0x22, 0x3f, 0x5b, 0x7a, 0xcd, 0x25, 0x7b, 0xc4, 0x35, 0x7d, 0xc2, 0xb9, 0xe3, 0xed,
	0x24, 0x9b, 0x73, 0x72, 0xd3, 0x75, 0x7c, 0x2e, 0x77, 0xf0, 0x65, 0xb8, 0x70, 0x75, 0x75, 0xeb,
	0xc3, 0xcd, 0x78, 0xff, 0x72, 0xc0, 0x77, 0x29, 0xd3, 0x1b, 0x50, 0xed, 0x58, 0x16, 0x0d, 0x3c,
	0xde, 0xd0, 0x9a, 0xda, 0x72, 0xcd, 0x48, 0x1f, 0xf5, 0x79, 0xa8, 0x70, 0x7a, 0x93, 0x78, 0x8d,
	0x92, 0xd8, 0x97, 0x0f, 0xf8, 0x06, 0xcc, 0x67, 0x26, 0x36, 0x1d, 0x9f, 0x1b, 0xe4, 0xab, 0x80,
	0xf8, 0x5c, 0xff, 0x18, 0xa6, 0x3b, 0xc2, 0xa2, 0x30, 0x53, 0x5f, 0x79, 0xb7, 0x35, 0x12, 0x79,
	0x2b, 0x77, 0xbf, 0x91, 0x9c, 0xba, 0x54, 0x09, 0xbf, 0x0e, 0x43, 0x84, 0xef, 0x69, 0xb0, 0x90,
	0xb3, 0xef, 0xf7, 0xa9, 0xe7, 0x13, 0x7d, 0x1d, 0xea, 0x5d, 0xea, 0xda, 0x84, 0x09, 0x42, 0xc9,
	0x2d, 0xef, 0x1c, 0x71, 0xcb, 0xba, 0xf8, 0x5a, 0xd8, 0x80, 0x6e, 0xb6, 0xd6, 0xdf, 0x82, 0xba,
	0x4d, 0xba, 0x9d, 0xc0, 0xe5, 0xa6, 0xed, 0xb0, 0x84, 0x1c, 0x24, 0x5b, 0x6b, 0x8e, 0x44, 0x12,
	0x21, 0xfc, 0xaf, 0x06, 0x8d, 0x0c, 0xc9, 0x86, 0xdd, 0x66, 0xa4, 0xc3, 0xc9, 0x98, 0xd8, 0xea,
	0x73, 0x50, 0x1e, 0x5e, 0x1e, 0x2f, 0xf5, 0x8f, 0x60, 0xca, 0x26, 0xbe, 0xd5, 0x28, 0x0b, 0x7b,
	0xef, 0x3d, 0xd7, 0x9e, 0xb0, 0xb6, 0x46, 0x7c, 0x8b, 0x39, 0x7d, 0xee, 0x50, 0xcf, 0x10, 0xc7,
	0xf4, 0x4f, 0xa0, 0x9a, 0x38, 0xbf, 0x31, 0x75, 0x8c, 0x32, 0xc2, 0xc2, 0xb6, 0xfc, 0xd8, 0x48,
	0x4f, 0xc5, 0xac, 0xbf, 0x0d, 0x11, 0xfe, 0x5e, 0x83, 0xc5, 0x11, 0xac, 0x13, 0x1f, 0x7c, 0x0a,
	0x60, 0x05, 0xcc, 0x94, 0x6a, 0x26, 0xd4, 0xdf, 0x3e, 0xd6, 0x05, 0x46, 0xcd, 0x0a, 0x98, 0x5c,
	0x8e, 0x20, 0xbe, 0x08, 0x48, 0xc6, 0xa9, 0x63, 0x0b, 0xf2, 0x35, 0xa3, 0xea, 0xca, 0xcb, 0x05,
	0xa6, 0x08, 0xe1, 0xbf, 0x0f, 0x7a, 0xe2, 0x33, 0xc2, 0x9c, 0xee, 0x60, 0x5c, 0x9e, 0xb8, 0x06,
	0xf5, 0x3d, 0x61, 0xd0, 0xe4, 0x83, 0x3e, 0x11, 0xc0, 0x66, 0x57, 0xf0, 0x73, 0x8c, 0x5c, 0x91,
	0x77, 0x5f, 0x1b, 0xf4, 0xc9, 0xa5, 0x0b, 0x57, 0x4c, 0xf9, 0x64, 0x26, 0x22, 0xc1, 0x5e, 0xf6,
	0x52, 0xbf, 0x08, 0x55, 0xdb, 0x97, 0x01, 0x26, 0x39, 0x4d, 0xdb, 0x7e, 0x1c, 0x5c, 0xf1, 0x0b,
	0x9f, 0x59, 0xe2, 0xc5, 0x94, 0x7c, 0xe1, 0x33, 0x2b, 0x89, 0xba, 0x7b, 0x21, 0xc2, 0x3f, 0x1c,
	0xd4, 0x3f, 0xe5, 0x9a, 0xe8, 0xbf, 0x08, 0x88, 0x11, 0x6e, 0x5a, 0xd4, 0x26, 0x82, 0xee, 0xab,
	0x46, 0x95, 0x11, 0xde, 0xa6, 0x36, 0x29, 0x86, 0x87, 0x40, 0x15, 0x21, 0xbc, 0xaf, 0xc1, 0xc5,
	0x0c, 0x55, 0x1a, 0x3a, 0x85, 0xa5, 0xc2, 0xd1, 0x11, 0x71, 0x3f, 0x44, 0xf8, 0x37, 0x35, 0x22,
	0x32, 0x3c, 0x89, 0x48, 0x89, 0x41, 0xed, 0x70, 0x6e, 0x95, 0xce, 0x9d, 0x5b, 0xe5, 0xb3, 0xe6,
	0xd6, 0xfd, 0x08, 0xe1, 0x87, 0x9a, 0x5a, 0x3b, 0xa9, 0x75, 0x73, 0x52, 0x12, 0x7e, 0x13, 0x22,
	0x7c, 0x43, 0xad, 0xb3, 0x02, 0x4b, 0x22, 0x5f, 0x2a, 0x96, 0x76, 0x26, 0xb1, 0x84, 0xf9, 0x08,
	0xe1, 0x7f, 0x34, 0x78, 0x3d, 0xb3, 0x7f, 0xdd, 0x73, 0x0b, 0x65, 0xfb, 0x02, 0xd4, 0xce, 0x3b,
	0x21, 0xc2, 0xa6, 0x92, 0x24, 0x29, 0xe5, 0xb1, 0x89, 0x7a, 0x27, 0x42, 0xf8, 0xb1, 0x2a, 0xea,
	0x1a, 0x71, 0x49, 0x91, 0x0d, 0xe9, 0xe8, 0x10, 0xfa, 0x2e, 0x44, 0x78, 0x57, 0xe1, 0x9b, 0xa2,
	0x19, 0x6f, 0xb3, 0x16, 0x37, 0x45, 0x08, 0xff, 0xae, 0x66, 0xce, 0x16, 0xdd, 0x9b, 0x08, 0x6d,
	0x7d, 0x01, 0xa6, 0x39, 0x55, 0x4a, 0x77, 0x85, 0xd3, 0xb8, 0xa4, 0xcf, 0x43, 0x85, 0xb2, 0xb8,
	0x1f, 0x56, 0x9a, 0xda, 0x72, 0xc5, 0x90, 0x0f, 0x31, 0xf2, 0xbb, 0xb2, 0x9e, 0x2f, 0xe4, 0x90,
	0x8f, 0x79, 0x9e, 0x39, 0xad, 0xe7, 0xee, 0x46, 0x08, 0xff, 0xa5, 0xea, 0xd9, 0xa6, 0xfd, 0xc1,
	0x0b, 0xaf, 0xa7, 0xde, 0x84, 0x19, 0x8f, 0xdc, 0x32, 0x33, 0x5b, 0xd3, 0x72, 0x6e, 0xf3, 0xc8,
	0xad, 0xcd, 0x21, 0xb7, 0xdb, 0x79, 0xc5, 0x25, 0xb7, 0x09, 0x2b, 0x7e, 0x3b, 0x5f, 0x0f, 0x37,
	0x7a, 0x7d, 0xca, 0xf8, 0x4b, 0x5d, 0x0f, 0x1f, 0x84, 0x08, 0x3f, 0x55, 0xa7, 0x86, 0x94, 0xf3,
	0xc4, 0x26, 0xc9, 0x07, 0x11, 0xc2, 0x3f, 0x97, 0x94, 0xb9, 0x21, 0x8e, 0x8d, 0x49, 0x75, 0xe1,
	0x31, 0xc7, 0xbe, 0xea, 0xb2, 0xea, 0x59, 0x5d, 0xf6, 0x30, 0x44, 0xf8, 0x27, 0x0d, 0xde, 0xc8,
	0xf8, 0xad, 0x76, 0xb8, 0xb5, 0x5b, 0x74, 0x9b, 0xc1, 0xf0, 0x4a, 0xca, 0x4b, 0xa6, 0x65, 0xb9,
	0x59, 0x5e, 0xae, 0x19, 0xf5, 0x44, 0xa8, 0xb4, 0x0b, 0x3c, 0x0a, 0x11, 0xfe, 0x55, 0x83, 0x37,
	0x47, 0x83, 0x3b, 0x7e, 0x3c, 0x6e, 0xc2, 0x0c, 0x61, 0x6c, 0x28, 0x61, 0xf2, 0xb3, 0x8f, 0x30,
	0x96, 0x4a, 0x98, 0xab, 0x0e, 0xe5, 0x73, 0xb4, 0xac, 0x47, 0x91, 0x50, 0xb2, 0x71, 0x10, 0xac,
	0x1c, 0x09, 0x36, 0x38, 0xe9, 0x9d, 0x73, 0x1c, 0x50, 0xbd, 0x5d, 0x3a, 0x8b, 0xb7, 0xf1, 0x9f,
	0x87, 0xdc, 0x5c, 0xf4, 0x88, 0xf6, 0x39, 0xcc, 0x05, 0xe2, 0x0a, 0xd3, 0xe1, 0xa4, 0x37, 0xf4,
	0x74, 0x7d, 0xe5, 0x83, 0xe3, 0x6c, 0xe7, 0xc4, 0x33, 0x66, 0x83, 0x6c, 0x9d, 0x0a, 0xfe, 0x78,
	0x64, 0x74, 0xe4, 0x66, 0xb0, 0x73, 0x46, 0x47, 0x2d, 0x96, 0x5e, 0x05, 0x7e, 0x0a, 0xb7, 0xa1,
	0xf8, 0x6c, 0x06, 0x36, 0x42, 0xf8, 0x0f, 0xf5, 0x67, 0x9e, 0x00, 0x5b, 0xec, 0x54, 0x73, 0x82,
	0x2c, 0x3b, 0xf5, 0x78, 0xb3, 0x1f, 0x22, 0xfc, 0x8b, 0x06, 0x4b, 0xa3, 0x78, 0x14, 0xde, 0x71,
	0x4f, 0x58, 0x36, 0xf6, 0x23, 0x84, 0xaf, 0x2b, 0x9d, 0x57, 0x40, 0x8c, 0x0b, 0xbf, 0x48, 0x43,
	0xb5, 0x3e, 0x6b, 0x07, 0xeb, 0x73, 0xbe, 0xe4, 0x96, 0xf2, 0x25, 0x17, 0xff, 0x7f, 0xc8, 0x85,
	0xc5, 0x0e, 0x52, 0x43, 0xf7, 0x94, 0x47, 0xba, 0x67, 0x4a, 0xed, 0x18, 0xdb, 0x30, 0x6b, 0xd1,
	0xfe, 0x40, 0x49, 0xb6, 0x8a, 0x88, 0xd9, 0xf7, 0x4f, 0x94, 0x6c, 0xa9, 0x40, 0xc6, 0x8c, 0x95,
	0xac, 0x52, 0x3d, 0x9f, 0x84, 0x08, 0xff, 0x78, 0xc8, 0xe7, 0x13, 0x99, 0xb2, 0xca, 0xb9, 0xfe,
	0xfe, 0x24, 0x42, 0xf8, 0x3f, 0x15, 0xda, 0x16, 0xb5, 0x9d, 0xee, 0x60, 0x7b, 0xe0, 0x59, 0x2f,
	0xf5, 0xa4, 0xf5, 0x34, 0x44, 0xab, 0x33, 0x5f, 0x40, 0x2f, 0x76, 0x84, 0xf8, 0x97, 0xf7, 0x59,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x8d, 0x4e, 0xf6, 0x46, 0x16, 0x00, 0x00,
}
