// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_common.proto

package matchproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PBMessageEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBMessageEmpty) Reset()         { *m = PBMessageEmpty{} }
func (m *PBMessageEmpty) String() string { return proto.CompactTextString(m) }
func (*PBMessageEmpty) ProtoMessage()    {}
func (*PBMessageEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f518fa9ec70b2478, []int{0}
}

func (m *PBMessageEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBMessageEmpty.Unmarshal(m, b)
}
func (m *PBMessageEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBMessageEmpty.Marshal(b, m, deterministic)
}
func (m *PBMessageEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBMessageEmpty.Merge(m, src)
}
func (m *PBMessageEmpty) XXX_Size() int {
	return xxx_messageInfo_PBMessageEmpty.Size(m)
}
func (m *PBMessageEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_PBMessageEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_PBMessageEmpty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PBMessageEmpty)(nil), "FunPlus.Common.Config.PBMessageEmpty")
}

func init() { proto.RegisterFile("msg_common.proto", fileDescriptor_f518fa9ec70b2478) }

var fileDescriptor_f518fa9ec70b2478 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2d, 0x4e, 0x8f,
	0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x75, 0x2b,
	0xcd, 0x0b, 0xc8, 0x29, 0x2d, 0xd6, 0x73, 0x86, 0x88, 0x3a, 0xe7, 0xe7, 0xa5, 0x65, 0xa6, 0x2b,
	0x09, 0x70, 0xf1, 0x05, 0x38, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0xba, 0xe6, 0x16, 0x94,
	0x54, 0x3a, 0xf1, 0x44, 0x71, 0xe5, 0x26, 0x96, 0x24, 0x67, 0x80, 0xb5, 0x01, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x45, 0x93, 0x98, 0x49, 0x00, 0x00, 0x00,
}
