// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_bi.proto

package matchproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//------------------------------------------------------------
// bi面板数据
type EBIResultStatus int32

const (
	EBIResultStatus_EBIResultNone   EBIResultStatus = 0
	EBIResultStatus_EBIResultSucess EBIResultStatus = 2
	EBIResultStatus_EBIResultFailed EBIResultStatus = 4
	EBIResultStatus_EBIResultQuit   EBIResultStatus = 8
)

var EBIResultStatus_name = map[int32]string{
	0: "EBIResultNone",
	2: "EBIResultSucess",
	4: "EBIResultFailed",
	8: "EBIResultQuit",
}

var EBIResultStatus_value = map[string]int32{
	"EBIResultNone":   0,
	"EBIResultSucess": 2,
	"EBIResultFailed": 4,
	"EBIResultQuit":   8,
}

func (x EBIResultStatus) Enum() *EBIResultStatus {
	p := new(EBIResultStatus)
	*p = x
	return p
}

func (x EBIResultStatus) String() string {
	return proto.EnumName(EBIResultStatus_name, int32(x))
}

func (x *EBIResultStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EBIResultStatus_value, data, "EBIResultStatus")
	if err != nil {
		return err
	}
	*x = EBIResultStatus(value)
	return nil
}

func (EBIResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{0}
}

type EBIItemUseStatus int32

const (
	EBIItemUseStatus_EBIItemAll    EBIItemUseStatus = 0
	EBIItemUseStatus_EBIItemUsed   EBIItemUseStatus = 1
	EBIItemUseStatus_EBIItemUnUsed EBIItemUseStatus = 2
)

var EBIItemUseStatus_name = map[int32]string{
	0: "EBIItemAll",
	1: "EBIItemUsed",
	2: "EBIItemUnUsed",
}

var EBIItemUseStatus_value = map[string]int32{
	"EBIItemAll":    0,
	"EBIItemUsed":   1,
	"EBIItemUnUsed": 2,
}

func (x EBIItemUseStatus) Enum() *EBIItemUseStatus {
	p := new(EBIItemUseStatus)
	*p = x
	return p
}

func (x EBIItemUseStatus) String() string {
	return proto.EnumName(EBIItemUseStatus_name, int32(x))
}

func (x *EBIItemUseStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EBIItemUseStatus_value, data, "EBIItemUseStatus")
	if err != nil {
		return err
	}
	*x = EBIItemUseStatus(value)
	return nil
}

func (EBIItemUseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{1}
}

type PBBIPanelBaseInfo struct {
	LevelVersion         *string  `protobuf:"bytes,1,opt,name=level_version,json=levelVersion" json:"level_version,omitempty"`
	ChallengeCnt         *int32   `protobuf:"varint,2,opt,name=challenge_cnt,json=challengeCnt" json:"challenge_cnt,omitempty"`
	SucessPercent        *float32 `protobuf:"fixed32,3,opt,name=sucess_percent,json=sucessPercent" json:"sucess_percent,omitempty"`
	AvgReshuffle         *float32 `protobuf:"fixed32,4,opt,name=avg_reshuffle,json=avgReshuffle" json:"avg_reshuffle,omitempty"`
	AvgDispare           *float32 `protobuf:"fixed32,5,opt,name=avg_dispare,json=avgDispare" json:"avg_dispare,omitempty"`
	FuuuPercent          *float32 `protobuf:"fixed32,6,opt,name=fuuu_percent,json=fuuuPercent" json:"fuuu_percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBBIPanelBaseInfo) Reset()         { *m = PBBIPanelBaseInfo{} }
func (m *PBBIPanelBaseInfo) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelBaseInfo) ProtoMessage()    {}
func (*PBBIPanelBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{0}
}

func (m *PBBIPanelBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelBaseInfo.Unmarshal(m, b)
}
func (m *PBBIPanelBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelBaseInfo.Marshal(b, m, deterministic)
}
func (m *PBBIPanelBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelBaseInfo.Merge(m, src)
}
func (m *PBBIPanelBaseInfo) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelBaseInfo.Size(m)
}
func (m *PBBIPanelBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelBaseInfo proto.InternalMessageInfo

func (m *PBBIPanelBaseInfo) GetLevelVersion() string {
	if m != nil && m.LevelVersion != nil {
		return *m.LevelVersion
	}
	return ""
}

func (m *PBBIPanelBaseInfo) GetChallengeCnt() int32 {
	if m != nil && m.ChallengeCnt != nil {
		return *m.ChallengeCnt
	}
	return 0
}

func (m *PBBIPanelBaseInfo) GetSucessPercent() float32 {
	if m != nil && m.SucessPercent != nil {
		return *m.SucessPercent
	}
	return 0
}

func (m *PBBIPanelBaseInfo) GetAvgReshuffle() float32 {
	if m != nil && m.AvgReshuffle != nil {
		return *m.AvgReshuffle
	}
	return 0
}

func (m *PBBIPanelBaseInfo) GetAvgDispare() float32 {
	if m != nil && m.AvgDispare != nil {
		return *m.AvgDispare
	}
	return 0
}

func (m *PBBIPanelBaseInfo) GetFuuuPercent() float32 {
	if m != nil && m.FuuuPercent != nil {
		return *m.FuuuPercent
	}
	return 0
}

type PBBIPanelAvgProgress struct {
	AvgProgressList      []float32 `protobuf:"fixed32,1,rep,name=avg_progress_list,json=avgProgressList" json:"avg_progress_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PBBIPanelAvgProgress) Reset()         { *m = PBBIPanelAvgProgress{} }
func (m *PBBIPanelAvgProgress) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelAvgProgress) ProtoMessage()    {}
func (*PBBIPanelAvgProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{1}
}

func (m *PBBIPanelAvgProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelAvgProgress.Unmarshal(m, b)
}
func (m *PBBIPanelAvgProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelAvgProgress.Marshal(b, m, deterministic)
}
func (m *PBBIPanelAvgProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelAvgProgress.Merge(m, src)
}
func (m *PBBIPanelAvgProgress) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelAvgProgress.Size(m)
}
func (m *PBBIPanelAvgProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelAvgProgress.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelAvgProgress proto.InternalMessageInfo

func (m *PBBIPanelAvgProgress) GetAvgProgressList() []float32 {
	if m != nil {
		return m.AvgProgressList
	}
	return nil
}

type PBBIPanelItemUseInfo struct {
	BoosterType          *int32   `protobuf:"varint,1,opt,name=booster_type,json=boosterType" json:"booster_type,omitempty"`
	Num                  *int32   `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBBIPanelItemUseInfo) Reset()         { *m = PBBIPanelItemUseInfo{} }
func (m *PBBIPanelItemUseInfo) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelItemUseInfo) ProtoMessage()    {}
func (*PBBIPanelItemUseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{2}
}

func (m *PBBIPanelItemUseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelItemUseInfo.Unmarshal(m, b)
}
func (m *PBBIPanelItemUseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelItemUseInfo.Marshal(b, m, deterministic)
}
func (m *PBBIPanelItemUseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelItemUseInfo.Merge(m, src)
}
func (m *PBBIPanelItemUseInfo) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelItemUseInfo.Size(m)
}
func (m *PBBIPanelItemUseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelItemUseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelItemUseInfo proto.InternalMessageInfo

func (m *PBBIPanelItemUseInfo) GetBoosterType() int32 {
	if m != nil && m.BoosterType != nil {
		return *m.BoosterType
	}
	return 0
}

func (m *PBBIPanelItemUseInfo) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type PBBIPanelItemUseStatus struct {
	UseCnt               *int32                  `protobuf:"varint,1,opt,name=use_cnt,json=useCnt" json:"use_cnt,omitempty"`
	ItemUseinfoList      []*PBBIPanelItemUseInfo `protobuf:"bytes,2,rep,name=item_useinfo_list,json=itemUseinfoList" json:"item_useinfo_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PBBIPanelItemUseStatus) Reset()         { *m = PBBIPanelItemUseStatus{} }
func (m *PBBIPanelItemUseStatus) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelItemUseStatus) ProtoMessage()    {}
func (*PBBIPanelItemUseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{3}
}

func (m *PBBIPanelItemUseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelItemUseStatus.Unmarshal(m, b)
}
func (m *PBBIPanelItemUseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelItemUseStatus.Marshal(b, m, deterministic)
}
func (m *PBBIPanelItemUseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelItemUseStatus.Merge(m, src)
}
func (m *PBBIPanelItemUseStatus) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelItemUseStatus.Size(m)
}
func (m *PBBIPanelItemUseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelItemUseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelItemUseStatus proto.InternalMessageInfo

func (m *PBBIPanelItemUseStatus) GetUseCnt() int32 {
	if m != nil && m.UseCnt != nil {
		return *m.UseCnt
	}
	return 0
}

func (m *PBBIPanelItemUseStatus) GetItemUseinfoList() []*PBBIPanelItemUseInfo {
	if m != nil {
		return m.ItemUseinfoList
	}
	return nil
}

type PBBIPanelSuccessInfo struct {
	AvgTime              *float32 `protobuf:"fixed32,1,opt,name=avg_time,json=avgTime" json:"avg_time,omitempty"`
	AvgRemainStep        *float32 `protobuf:"fixed32,2,opt,name=avg_remain_step,json=avgRemainStep" json:"avg_remain_step,omitempty"`
	AvgCoinNum           *float32 `protobuf:"fixed32,3,opt,name=avg_coin_num,json=avgCoinNum" json:"avg_coin_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBBIPanelSuccessInfo) Reset()         { *m = PBBIPanelSuccessInfo{} }
func (m *PBBIPanelSuccessInfo) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelSuccessInfo) ProtoMessage()    {}
func (*PBBIPanelSuccessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{4}
}

func (m *PBBIPanelSuccessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelSuccessInfo.Unmarshal(m, b)
}
func (m *PBBIPanelSuccessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelSuccessInfo.Marshal(b, m, deterministic)
}
func (m *PBBIPanelSuccessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelSuccessInfo.Merge(m, src)
}
func (m *PBBIPanelSuccessInfo) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelSuccessInfo.Size(m)
}
func (m *PBBIPanelSuccessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelSuccessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelSuccessInfo proto.InternalMessageInfo

func (m *PBBIPanelSuccessInfo) GetAvgTime() float32 {
	if m != nil && m.AvgTime != nil {
		return *m.AvgTime
	}
	return 0
}

func (m *PBBIPanelSuccessInfo) GetAvgRemainStep() float32 {
	if m != nil && m.AvgRemainStep != nil {
		return *m.AvgRemainStep
	}
	return 0
}

func (m *PBBIPanelSuccessInfo) GetAvgCoinNum() float32 {
	if m != nil && m.AvgCoinNum != nil {
		return *m.AvgCoinNum
	}
	return 0
}

type PBBIPanelTargetRemain struct {
	TargetType           *int32   `protobuf:"varint,1,opt,name=target_type,json=targetType" json:"target_type,omitempty"`
	AvgRemain            *float32 `protobuf:"fixed32,2,opt,name=avg_remain,json=avgRemain" json:"avg_remain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBBIPanelTargetRemain) Reset()         { *m = PBBIPanelTargetRemain{} }
func (m *PBBIPanelTargetRemain) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelTargetRemain) ProtoMessage()    {}
func (*PBBIPanelTargetRemain) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{5}
}

func (m *PBBIPanelTargetRemain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelTargetRemain.Unmarshal(m, b)
}
func (m *PBBIPanelTargetRemain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelTargetRemain.Marshal(b, m, deterministic)
}
func (m *PBBIPanelTargetRemain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelTargetRemain.Merge(m, src)
}
func (m *PBBIPanelTargetRemain) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelTargetRemain.Size(m)
}
func (m *PBBIPanelTargetRemain) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelTargetRemain.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelTargetRemain proto.InternalMessageInfo

func (m *PBBIPanelTargetRemain) GetTargetType() int32 {
	if m != nil && m.TargetType != nil {
		return *m.TargetType
	}
	return 0
}

func (m *PBBIPanelTargetRemain) GetAvgRemain() float32 {
	if m != nil && m.AvgRemain != nil {
		return *m.AvgRemain
	}
	return 0
}

type PBBIPanelFailedInfo struct {
	AvgTargetremainList  []*PBBIPanelTargetRemain `protobuf:"bytes,1,rep,name=avg_targetremain_list,json=avgTargetremainList" json:"avg_targetremain_list,omitempty"`
	QuitCnt              *int32                   `protobuf:"varint,2,opt,name=quit_cnt,json=quitCnt" json:"quit_cnt,omitempty"`
	QuitPercent          *float32                 `protobuf:"fixed32,3,opt,name=quit_percent,json=quitPercent" json:"quit_percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PBBIPanelFailedInfo) Reset()         { *m = PBBIPanelFailedInfo{} }
func (m *PBBIPanelFailedInfo) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelFailedInfo) ProtoMessage()    {}
func (*PBBIPanelFailedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{6}
}

func (m *PBBIPanelFailedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelFailedInfo.Unmarshal(m, b)
}
func (m *PBBIPanelFailedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelFailedInfo.Marshal(b, m, deterministic)
}
func (m *PBBIPanelFailedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelFailedInfo.Merge(m, src)
}
func (m *PBBIPanelFailedInfo) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelFailedInfo.Size(m)
}
func (m *PBBIPanelFailedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelFailedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelFailedInfo proto.InternalMessageInfo

func (m *PBBIPanelFailedInfo) GetAvgTargetremainList() []*PBBIPanelTargetRemain {
	if m != nil {
		return m.AvgTargetremainList
	}
	return nil
}

func (m *PBBIPanelFailedInfo) GetQuitCnt() int32 {
	if m != nil && m.QuitCnt != nil {
		return *m.QuitCnt
	}
	return 0
}

func (m *PBBIPanelFailedInfo) GetQuitPercent() float32 {
	if m != nil && m.QuitPercent != nil {
		return *m.QuitPercent
	}
	return 0
}

type PBBIPanelInfoRequest struct {
	Author               *PBM3LevelAuthor    `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	ResultStatus         *int32              `protobuf:"varint,2,opt,name=result_status,json=resultStatus" json:"result_status,omitempty"`
	UseStatus            *EBIItemUseStatus   `protobuf:"varint,3,opt,name=use_status,json=useStatus,enum=FunPlus.Common.Config.EBIItemUseStatus,def=0" json:"use_status,omitempty"`
	Desc                 *PBLevelDescription `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PBBIPanelInfoRequest) Reset()         { *m = PBBIPanelInfoRequest{} }
func (m *PBBIPanelInfoRequest) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelInfoRequest) ProtoMessage()    {}
func (*PBBIPanelInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{7}
}

func (m *PBBIPanelInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelInfoRequest.Unmarshal(m, b)
}
func (m *PBBIPanelInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelInfoRequest.Marshal(b, m, deterministic)
}
func (m *PBBIPanelInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelInfoRequest.Merge(m, src)
}
func (m *PBBIPanelInfoRequest) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelInfoRequest.Size(m)
}
func (m *PBBIPanelInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelInfoRequest proto.InternalMessageInfo

const Default_PBBIPanelInfoRequest_UseStatus EBIItemUseStatus = EBIItemUseStatus_EBIItemAll

func (m *PBBIPanelInfoRequest) GetAuthor() *PBM3LevelAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PBBIPanelInfoRequest) GetResultStatus() int32 {
	if m != nil && m.ResultStatus != nil {
		return *m.ResultStatus
	}
	return 0
}

func (m *PBBIPanelInfoRequest) GetUseStatus() EBIItemUseStatus {
	if m != nil && m.UseStatus != nil {
		return *m.UseStatus
	}
	return Default_PBBIPanelInfoRequest_UseStatus
}

func (m *PBBIPanelInfoRequest) GetDesc() *PBLevelDescription {
	if m != nil {
		return m.Desc
	}
	return nil
}

type PBBIPanelInfoResponse struct {
	BaseInfo             *PBBIPanelBaseInfo      `protobuf:"bytes,1,opt,name=base_info,json=baseInfo" json:"base_info,omitempty"`
	AvgProgress          *PBBIPanelAvgProgress   `protobuf:"bytes,2,opt,name=avg_progress,json=avgProgress" json:"avg_progress,omitempty"`
	ItemUseStatus        *PBBIPanelItemUseStatus `protobuf:"bytes,3,opt,name=item_use_status,json=itemUseStatus" json:"item_use_status,omitempty"`
	SuccessInfo          *PBBIPanelSuccessInfo   `protobuf:"bytes,4,opt,name=success_info,json=successInfo" json:"success_info,omitempty"`
	FailedInfo           *PBBIPanelFailedInfo    `protobuf:"bytes,5,opt,name=failed_info,json=failedInfo" json:"failed_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PBBIPanelInfoResponse) Reset()         { *m = PBBIPanelInfoResponse{} }
func (m *PBBIPanelInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PBBIPanelInfoResponse) ProtoMessage()    {}
func (*PBBIPanelInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{8}
}

func (m *PBBIPanelInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBIPanelInfoResponse.Unmarshal(m, b)
}
func (m *PBBIPanelInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBIPanelInfoResponse.Marshal(b, m, deterministic)
}
func (m *PBBIPanelInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBIPanelInfoResponse.Merge(m, src)
}
func (m *PBBIPanelInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PBBIPanelInfoResponse.Size(m)
}
func (m *PBBIPanelInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBIPanelInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBBIPanelInfoResponse proto.InternalMessageInfo

func (m *PBBIPanelInfoResponse) GetBaseInfo() *PBBIPanelBaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

func (m *PBBIPanelInfoResponse) GetAvgProgress() *PBBIPanelAvgProgress {
	if m != nil {
		return m.AvgProgress
	}
	return nil
}

func (m *PBBIPanelInfoResponse) GetItemUseStatus() *PBBIPanelItemUseStatus {
	if m != nil {
		return m.ItemUseStatus
	}
	return nil
}

func (m *PBBIPanelInfoResponse) GetSuccessInfo() *PBBIPanelSuccessInfo {
	if m != nil {
		return m.SuccessInfo
	}
	return nil
}

func (m *PBBIPanelInfoResponse) GetFailedInfo() *PBBIPanelFailedInfo {
	if m != nil {
		return m.FailedInfo
	}
	return nil
}

type PBBISessionBegin struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Seed                 *int32   `protobuf:"varint,2,opt,name=seed" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBBISessionBegin) Reset()         { *m = PBBISessionBegin{} }
func (m *PBBISessionBegin) String() string { return proto.CompactTextString(m) }
func (*PBBISessionBegin) ProtoMessage()    {}
func (*PBBISessionBegin) Descriptor() ([]byte, []int) {
	return fileDescriptor_014b410dbbb6b690, []int{9}
}

func (m *PBBISessionBegin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBISessionBegin.Unmarshal(m, b)
}
func (m *PBBISessionBegin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBISessionBegin.Marshal(b, m, deterministic)
}
func (m *PBBISessionBegin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBISessionBegin.Merge(m, src)
}
func (m *PBBISessionBegin) XXX_Size() int {
	return xxx_messageInfo_PBBISessionBegin.Size(m)
}
func (m *PBBISessionBegin) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBISessionBegin.DiscardUnknown(m)
}

var xxx_messageInfo_PBBISessionBegin proto.InternalMessageInfo

func (m *PBBISessionBegin) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PBBISessionBegin) GetSeed() int32 {
	if m != nil && m.Seed != nil {
		return *m.Seed
	}
	return 0
}

func init() {
	proto.RegisterEnum("FunPlus.Common.Config.EBIResultStatus", EBIResultStatus_name, EBIResultStatus_value)
	proto.RegisterEnum("FunPlus.Common.Config.EBIItemUseStatus", EBIItemUseStatus_name, EBIItemUseStatus_value)
	proto.RegisterType((*PBBIPanelBaseInfo)(nil), "FunPlus.Common.Config.PBBIPanelBaseInfo")
	proto.RegisterType((*PBBIPanelAvgProgress)(nil), "FunPlus.Common.Config.PBBIPanelAvgProgress")
	proto.RegisterType((*PBBIPanelItemUseInfo)(nil), "FunPlus.Common.Config.PBBIPanelItemUseInfo")
	proto.RegisterType((*PBBIPanelItemUseStatus)(nil), "FunPlus.Common.Config.PBBIPanelItemUseStatus")
	proto.RegisterType((*PBBIPanelSuccessInfo)(nil), "FunPlus.Common.Config.PBBIPanelSuccessInfo")
	proto.RegisterType((*PBBIPanelTargetRemain)(nil), "FunPlus.Common.Config.PBBIPanelTargetRemain")
	proto.RegisterType((*PBBIPanelFailedInfo)(nil), "FunPlus.Common.Config.PBBIPanelFailedInfo")
	proto.RegisterType((*PBBIPanelInfoRequest)(nil), "FunPlus.Common.Config.PBBIPanelInfoRequest")
	proto.RegisterType((*PBBIPanelInfoResponse)(nil), "FunPlus.Common.Config.PBBIPanelInfoResponse")
	proto.RegisterType((*PBBISessionBegin)(nil), "FunPlus.Common.Config.PBBISessionBegin")
}

func init() { proto.RegisterFile("msg_bi.proto", fileDescriptor_014b410dbbb6b690) }

var fileDescriptor_014b410dbbb6b690 = []byte{
	// 902 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0x23, 0x45,
	0x10, 0x5d, 0xdb, 0x71, 0x3e, 0x6a, 0xc6, 0xf1, 0xa4, 0x43, 0xc0, 0xac, 0x84, 0x70, 0x8c, 0x58,
	0x4c, 0x00, 0x1f, 0xcc, 0x05, 0xad, 0x04, 0x52, 0x9c, 0x4d, 0x24, 0x6b, 0x97, 0xc8, 0x74, 0xb2,
	0xac, 0xc4, 0x65, 0x98, 0x8c, 0xcb, 0x93, 0x16, 0x33, 0xdd, 0xb3, 0xd3, 0xdd, 0x96, 0x22, 0x84,
	0x94, 0x33, 0x77, 0xee, 0x5c, 0xf9, 0x01, 0xfc, 0x2c, 0xfe, 0x03, 0xea, 0xee, 0xf1, 0x64, 0xbc,
	0xda, 0x28, 0xb9, 0x4d, 0x3f, 0x57, 0x57, 0x57, 0xbd, 0x7a, 0xaf, 0x0c, 0x7e, 0x26, 0x93, 0xf0,
	0x8a, 0x8d, 0xf2, 0x42, 0x28, 0x41, 0x0e, 0xce, 0x34, 0x9f, 0xa5, 0x5a, 0x8e, 0x4e, 0x44, 0x96,
	0x09, 0x3e, 0x3a, 0x11, 0x7c, 0xc1, 0x92, 0xa7, 0xbb, 0x36, 0x28, 0x92, 0xe8, 0xc2, 0x9e, 0x06,
	0xe6, 0x8c, 0x73, 0xa6, 0x44, 0xb1, 0x42, 0x52, 0x5c, 0x62, 0x1a, 0xa6, 0x4c, 0x2a, 0x87, 0x0c,
	0xfe, 0x6b, 0xc0, 0xde, 0x6c, 0x32, 0x99, 0xce, 0x22, 0x8e, 0xe9, 0x24, 0x92, 0x38, 0xe5, 0x0b,
	0x41, 0x3e, 0x83, 0x8e, 0x8b, 0x5c, 0x62, 0x21, 0x99, 0xe0, 0xbd, 0x46, 0xbf, 0x31, 0xdc, 0xa1,
	0xbe, 0x05, 0x7f, 0x76, 0x98, 0x09, 0x8a, 0xaf, 0xa3, 0x34, 0x45, 0x9e, 0x60, 0x18, 0x73, 0xd5,
	0x6b, 0xf6, 0x1b, 0xc3, 0x36, 0xf5, 0x2b, 0xf0, 0x84, 0x2b, 0xf2, 0x39, 0xec, 0x4a, 0x1d, 0xa3,
	0x94, 0x61, 0x8e, 0x45, 0x8c, 0x5c, 0xf5, 0x5a, 0xfd, 0xc6, 0xb0, 0x49, 0x3b, 0x0e, 0x9d, 0x39,
	0xd0, 0xe4, 0x8a, 0x96, 0x49, 0x58, 0xa0, 0xbc, 0xd6, 0x8b, 0x45, 0x8a, 0xbd, 0x0d, 0x1b, 0xe5,
	0x47, 0xcb, 0x84, 0xae, 0x30, 0xf2, 0x29, 0x78, 0x26, 0x68, 0xce, 0x64, 0x1e, 0x15, 0xd8, 0x6b,
	0xdb, 0x10, 0x88, 0x96, 0xc9, 0x0b, 0x87, 0x90, 0x43, 0xf0, 0x17, 0x5a, 0xeb, 0xea, 0xa9, 0x4d,
	0x1b, 0xe1, 0x19, 0xac, 0x7c, 0x68, 0x30, 0x81, 0x0f, 0xaa, 0x76, 0x8f, 0x97, 0xc9, 0xac, 0x10,
	0x49, 0x81, 0x52, 0x92, 0x23, 0xd8, 0x33, 0xb9, 0xf3, 0xf2, 0x6c, 0x29, 0xea, 0x35, 0xfa, 0xad,
	0x61, 0x93, 0x76, 0xa3, 0xbb, 0xb8, 0x57, 0x4c, 0xaa, 0xc1, 0xcb, 0x5a, 0x8e, 0xa9, 0xc2, 0xec,
	0x75, 0xc9, 0xda, 0x21, 0xf8, 0x57, 0x42, 0x48, 0x85, 0x45, 0xa8, 0x6e, 0x72, 0xb4, 0xa4, 0xb5,
	0xa9, 0x57, 0x62, 0x97, 0x37, 0x39, 0x92, 0x00, 0x5a, 0x5c, 0x67, 0x25, 0x53, 0xe6, 0x73, 0xf0,
	0x67, 0x03, 0x3e, 0x7c, 0x37, 0xdb, 0x85, 0x8a, 0x94, 0x96, 0xe4, 0x23, 0xd8, 0xd2, 0xd2, 0x51,
	0xeb, 0x52, 0x6d, 0x6a, 0x69, 0x49, 0x7d, 0x03, 0x7b, 0x4c, 0x61, 0x16, 0x6a, 0x89, 0x8c, 0x2f,
	0x84, 0x2b, 0xb6, 0xd9, 0x6f, 0x0d, 0xbd, 0xf1, 0x57, 0xa3, 0xf7, 0x6a, 0x63, 0xf4, 0xbe, 0x82,
	0x69, 0x97, 0xb9, 0x83, 0x49, 0x62, 0x3b, 0xfb, 0xbd, 0xd6, 0xd9, 0x85, 0x8e, 0xcd, 0x84, 0x6c,
	0x67, 0x1f, 0xc3, 0xb6, 0x61, 0x47, 0xb1, 0xcc, 0x75, 0xd5, 0xa4, 0x5b, 0xd1, 0x32, 0xb9, 0x64,
	0x19, 0x92, 0x67, 0xd0, 0x75, 0x93, 0xcb, 0x22, 0xc6, 0x43, 0xa9, 0x30, 0xb7, 0xdd, 0x35, 0x69,
	0xc7, 0xce, 0xce, 0xa0, 0x17, 0x0a, 0x73, 0xd2, 0x07, 0x33, 0xcc, 0x30, 0x16, 0x8c, 0x87, 0x86,
	0x82, 0x56, 0x35, 0xbd, 0x13, 0xc1, 0xf8, 0xb9, 0xce, 0x06, 0x6f, 0xe0, 0xa0, 0x7a, 0xfc, 0x32,
	0x2a, 0x12, 0x54, 0xee, 0xba, 0x99, 0xbb, 0xb2, 0xe7, 0x3a, 0xad, 0xe0, 0x20, 0xcb, 0xea, 0x27,
	0x00, 0x77, 0x35, 0x94, 0xcf, 0xef, 0x54, 0xcf, 0x0f, 0xfe, 0x6d, 0xc0, 0x7e, 0x95, 0xf9, 0x2c,
	0x62, 0x29, 0xce, 0x6d, 0x57, 0xbf, 0xc2, 0x81, 0xed, 0xca, 0x26, 0x2a, 0x1b, 0xa8, 0xe6, 0xee,
	0x8d, 0xbf, 0x7e, 0x88, 0xca, 0x7a, 0x91, 0x74, 0xdf, 0x10, 0x52, 0xcb, 0x64, 0xf8, 0x34, 0xbc,
	0xbd, 0xd5, 0x4c, 0xd5, 0xdc, 0xb1, 0x65, 0xce, 0x66, 0x86, 0x87, 0xe0, 0xdb, 0x9f, 0xd6, 0x6d,
	0xe1, 0x19, 0x6c, 0xa5, 0xd5, 0xbf, 0x9a, 0x75, 0xa1, 0x99, 0x81, 0xe1, 0x5b, 0x8d, 0x52, 0x91,
	0x1f, 0x60, 0x33, 0xd2, 0xea, 0x5a, 0x14, 0x96, 0x0b, 0x6f, 0xfc, 0xec, 0xde, 0x4a, 0x7f, 0xfc,
	0xf6, 0x95, 0xb1, 0xec, 0xb1, 0x8d, 0xa6, 0xe5, 0x2d, 0xe3, 0xb6, 0x02, 0xa5, 0x4e, 0x55, 0x28,
	0xad, 0xd2, 0x56, 0xce, 0x75, 0x60, 0xa9, 0x3e, 0x0a, 0x60, 0xd4, 0x57, 0x46, 0x98, 0xf2, 0x76,
	0xc7, 0x5f, 0xdc, 0xf3, 0xd0, 0xe9, 0x64, 0xba, 0x26, 0xdd, 0xe7, 0x50, 0x22, 0xc7, 0x69, 0x4a,
	0x77, 0x74, 0xa5, 0xe8, 0xef, 0x61, 0x63, 0x8e, 0x32, 0xb6, 0xee, 0xf6, 0xc6, 0x5f, 0xde, 0x5b,
	0xb6, 0x2d, 0xfa, 0x05, 0xca, 0xb8, 0x60, 0xb9, 0x62, 0x82, 0x53, 0x7b, 0xed, 0x79, 0xfb, 0xf6,
	0x8f, 0xdb, 0x5b, 0x7f, 0xf0, 0x4f, 0xab, 0xa6, 0x14, 0xc7, 0x8b, 0xcc, 0x05, 0x97, 0x48, 0x4e,
	0x61, 0xc7, 0xec, 0xbf, 0xd0, 0x08, 0xba, 0xe4, 0x66, 0xf8, 0xd0, 0x14, 0x57, 0x4b, 0x8f, 0x6e,
	0x5f, 0xad, 0xd6, 0xdf, 0xb9, 0xd3, 0xea, 0x6a, 0x19, 0x58, 0x7a, 0x1e, 0x61, 0xad, 0xda, 0x3e,
	0xa1, 0x5e, 0x6d, 0x69, 0x90, 0xd7, 0xd0, 0x5d, 0xf9, 0xb5, 0xce, 0xa7, 0x37, 0xfe, 0xe6, 0x91,
	0x6e, 0x75, 0xf4, 0xd1, 0x0e, 0x5b, 0xdb, 0x0f, 0xe7, 0xe0, 0x4b, 0x67, 0x52, 0xd7, 0xf0, 0xc6,
	0xe3, 0xca, 0xac, 0x19, 0x9b, 0x7a, 0xb2, 0xe6, 0xf2, 0x97, 0xe0, 0x2d, 0xac, 0x3b, 0x5c, 0xba,
	0xb6, 0x4d, 0x77, 0xf4, 0x50, 0xba, 0x3b, 0x43, 0x51, 0x58, 0x54, 0xdf, 0x76, 0x56, 0x7f, 0xfb,
	0x83, 0xef, 0x20, 0x30, 0x91, 0x17, 0x28, 0xcd, 0x7f, 0xc6, 0x04, 0x13, 0xc6, 0xcd, 0x12, 0xfc,
	0x0d, 0x6f, 0x4a, 0x1f, 0x9b, 0x4f, 0x42, 0x60, 0x43, 0x22, 0xce, 0x4b, 0x1d, 0xda, 0xef, 0xa3,
	0x08, 0xba, 0xa7, 0x93, 0x29, 0xad, 0x4b, 0x72, 0x0f, 0x3a, 0x15, 0x74, 0x2e, 0x38, 0x06, 0x4f,
	0xc8, 0x7e, 0x3d, 0xca, 0xfe, 0xa5, 0x04, 0xcd, 0x35, 0xd0, 0x95, 0x17, 0x6c, 0xac, 0x5d, 0xfe,
	0x49, 0x33, 0x15, 0x6c, 0x1f, 0x9d, 0x41, 0xf0, 0xae, 0x72, 0xc9, 0x2e, 0xd4, 0xb4, 0x1b, 0x3c,
	0x21, 0x5d, 0xf0, 0xee, 0x62, 0xe6, 0x41, 0xa3, 0xcc, 0x63, 0x01, 0x6e, 0xa1, 0xe6, 0xc4, 0xff,
	0x05, 0xb2, 0x48, 0xc5, 0xd7, 0xf6, 0x2f, 0xf5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xad,
	0x40, 0x23, 0xac, 0x07, 0x00, 0x00,
}
